### ISSUE TITLE
logrotate lens fails to parse when no-space between file and {

### ISSUE THREAD

**Issue by xdelaruelle** [hercules-team/augeas#123]
Hello,

We are using augeas-1.0.0-5.el6_5.1 on a RedHat 6.5 system. Our syslog-ng logrotate config file looks like:

    /var/log/syslog /var/log/secure{
        compress
        sharedscripts
        postrotate
        /bin/kill -HUP `cat /var/run/syslog-ng.pid 2> /dev/null` 2> /dev/null || true
        endscript
    }

Augeas is not able to parse this file:

    augtool> print //files/etc/logrotate.d/syslog-ng
    /augeas/files/etc/logrotate.d/syslog-ng
    /augeas/files/etc/logrotate.d/syslog-ng/path = "/files/etc/logrotate.d/syslog-ng"
    /augeas/files/etc/logrotate.d/syslog-ng/mtime = "1399378192"
    /augeas/files/etc/logrotate.d/syslog-ng/lens = "@Logrotate"
    /augeas/files/etc/logrotate.d/syslog-ng/lens/info = "/usr/share/augeas/lenses/dist/logrotate.aug:117.13-.56:"
    /augeas/files/etc/logrotate.d/syslog-ng/error = "parse_failed"
    /augeas/files/etc/logrotate.d/syslog-ng/error/pos = "0"
    /augeas/files/etc/logrotate.d/syslog-ng/error/line = "1"
    /augeas/files/etc/logrotate.d/syslog-ng/error/char = "0"
    /augeas/files/etc/logrotate.d/syslog-ng/error/lens = "/usr/share/augeas/lenses/dist/logrotate.aug:117.13-.56:"
    /augeas/files/etc/logrotate.d/syslog-ng/error/message = "Iterated lens matched less than it should"

This issue seems to be caused by the lack of white-space between file list and "{". It would be nice if logrotate lens can handle this kind of use case.

Regards,
Xavier

**Comment by lutter** [comment]
Thanks for reporting this problem.

Fixed in 6326f0e2
