### ISSUE TITLE
Dhclient: gethostname() function not supported

### ISSUE THREAD

**Issue by raphink** [hercules-team/augeas#141]
```
send host-name = gethostname();
```

is not supported in `dhclient.conf`.

**Comment by jaqx0r** [comment]
https://github.com/hercules-team/augeas/commit/2202c8b4dffd9083bf7bc804155d01803bc4bf31 appears to fix this.

I'm running 1.2.0 because dbeian is old, and patching the latest lens file in has fixed the issue.

**Comment by raphink** [comment]
That is quite possible.

**Comment by domcleal** [comment]
Fixed in 1.5.0 according to above comment/commit.
