### ISSUE TITLE
Httpd.aug: mod_version operators are not supported

### ISSUE THREAD

**Issue by alex-eoi** [hercules-team/augeas#154]
As described in [mod_version's documentation](http://httpd.apache.org/docs/2.2/mod/mod_version.html) one is able to use different operators with mod_version. Example:

```
<IfVersion 2.1.0>
# current httpd version is exactly 2.1.0
</IfVersion>

<IfVersion >= 2.2>
# use really new features :-)
</IfVersion> 
```

Unfortunately the augeas lense throws errors when using the greater-equal operator. After looking at the augeas lense i'm completely confused because in my opinion sep_eq should be extended with all valid operators but this definition is never used inside the lense (or did i get something wrong here?)

Here's a short test case for confirmation:

```
module Test_httpd =

let versioncheck = "
<IfVersion = 2.1>
<IfModule !proxy_ajp_module>
LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
</IfModule>
</IfVersion>

<IfVersion >= 2.4>
<IfModule !proxy_ajp_module>
LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
</IfModule>
</IfVersion>
"

test Httpd.lns get versioncheck =
  { }
  { "IfVersion"
    { "arg" = "=" }
    { "arg" = "2.1" }
    { "IfModule"
      { "arg" = "!proxy_ajp_module" }
      { "directive" = "LoadModule"
        { "arg" = "proxy_ajp_module" }
        { "arg" = "modules/mod_proxy_ajp.so" }
      }
    }
  }
  { "IfVersion"
    { "arg" = ">=" }
    { "arg" = "2.4" }
    { "IfModule"
      { "arg" = "!proxy_ajp_module" }
      { "directive" = "LoadModule"
        { "arg" = "proxy_ajp_module" }
        { "arg" = "modules/mod_proxy_ajp.so" }
      }
    }
  }
```

**Comment by chriscroome** [comment]
Is there an issue with a less than in a `<IfVersion>` tag?

```apache
    <IfVersion < 2.3>
        order allow,deny
        allow from all
    </IfVersion>
``` 
I can't see a test case for this.

See also:

* https://github.com/letsencrypt/letsencrypt/issues/1264
* https://github.com/letsencrypt/letsencrypt/issues/1294

**Comment by domcleal** [comment]
@chriscroome indeed, I can't see a test case for a less than symbol, but after adding one, the test passes fine on master.  I'll comment directly on the LE bug reports.

**Comment by ConfVD** [comment]
I was supposed to report the same issue in Python-augeas. Is there a fix?
