### ISSUE TITLE
Provide full set of XPath operations

### ISSUE THREAD

**Issue by krichter722** [hercules-team/augeas#164]
I'd be great to enhance this (already) very great (in both idea and realization) project by providing the full set of XPath operations rather than the limited set (which I don't find completely documented, BTW). It'd be great if one could query values like `/files/etc/hosts/canonical[text()="example.com"]`. This implies changing from index query in the form of `/path/to/_number_/key` to XPath-like index access in the form of `/path/to[_number_]/key` which shouldn't have any disadvantages.

**Comment by lutter** [comment]
Closing this since there isn't anything concrete to do. Please open issues describing specific functionality you'd like to see added.
