### ISSUE TITLE
cannot insert compress node in logrotate.conf

### ISSUE THREAD

**Issue by timdaman** [hercules-team/augeas#181]
I looks like there may be an issue in the logrotate.conf lens that prevents adding a glocal compress option in logrotoate.conf. I tried something like so

```
ins compress after /files/etc/logrotate.conf/#comment[.='compress']
clear /files/etc/logrotate.conf/compress
```

I get the following error

```
/augeas/files/etc/logrotate.conf/error = "put_failed"
/augeas/files/etc/logrotate.conf/error/path = "/files/etc/logrotate.conf"
/augeas/files/etc/logrotate.conf/error/lens = "/usr/share/augeas/lenses/dist/logrotate.aug:111.13-.54:"
/augeas/files/etc/logrotate.conf/error/message = "Malformed child node 'compress'"
```

When I set a value for the compress label the error clears so I think there is an issue with the lens requiring a value for the compress label. 

I am not great at creating lenses but I did hack up the code in logrotate.aug a bit and by changing 

```
    | select_to_eol "compress" /(no)?compress/
```

to

```
    | flag_to_eol "compress" 
    | flag_to_eol "nocompress" 
```

If this looks good to everyone I can submit a pull request to make this change.

**Comment by lutter** [comment]
The problem is that the existing lens expects you to set `/files/etc/logrotate.conf/compress` to either `compress` or `nocompress`. Unfortunately, changing this in the way you suggest would be a backwards incompatible change.

**Comment by lutter** [comment]
While this would be an improvement, it's not worth breaking backwards compatibility for this lens.
