### ISSUE TITLE
Augeas 1.3.0 Httpd lens broke parsing RedHat's ssl.conf

### ISSUE THREAD

**Issue by smithj4** [hercules-team/augeas#191]
Augeas 1.3.0 fails to parse RedHat's ssl.conf file:

rpm -q augeas
augeas-1.3.0-1.el6.x86_64

augtool print /augeas/files/etc/httpd/conf.d/ssl.conf/error
/augeas/files/etc/httpd/conf.d/ssl.conf/error = "parse_failed"
/augeas/files/etc/httpd/conf.d/ssl.conf/error/pos = "2711"
/augeas/files/etc/httpd/conf.d/ssl.conf/error/line = "77"
/augeas/files/etc/httpd/conf.d/ssl.conf/error/char = "0"
/augeas/files/etc/httpd/conf.d/ssl.conf/error/lens = "/usr/share/augeas/lenses/dist/httpd.aug:97.10-.44:"
/augeas/files/etc/httpd/conf.d/ssl.conf/error/message = "Syntax error"

Line 77 of /etc/httpd/conf.d/ssl.conf is the commented DocumentRoot line:
<pre>
##
##

&lt;VirtualHost _default_:443&gt;

# General setup for the virtual host, inherited from global configuration
#DocumentRoot "/var/www/html"     &lt;--- line 77
#ServerName www.example.com:443
</pre>

Version 1.2.0 did not have this problem:

rpm -q augeas
augeas-1.2.0-1.el6.x86_64

augtool print /augeas/files/etc/httpd/conf.d/ssl.conf/error
[no output]

**Comment by lutter** [comment]
@raphink can you have a look at this as you wrote commit fb749ea ?

**Comment by lutter** [comment]
This is fixed as of commit 34980ae5
