### ISSUE TITLE
configure?

### ISSUE THREAD

**Issue by ggardella** [hercules-team/augeas#201]
Hey, just downloaded augeas for the first time. The build instructions tell me to run ./configure from the root of the source code. This file does not appear to exist. The INSTALL notes briefly mention autoconf generating 'configure' from 'configure.ac'. Can somebody clarify here? Thanks!

**Comment by domcleal** [comment]
Run `./autogen.sh && ./configure` if you're checking it out from git, but if you have a release tarball from http://download.augeas.net/ then just `./configure` is correct.

**Comment by lutter** [comment]
Closing this since this doesn't seem to be a bug. Please reopen if you disagree.
