### ISSUE TITLE
does augeas lense test clear update-notifier/updates-available?

### ISSUE THREAD

**Issue by michag86** [hercules-team/augeas#204]
end of /lenses/tests/test_aptconf.aug :

 test AptConf.lns get complex_elem =
{ "DPkg" { "Post-Invoke"
{ "@elem" = "if [ -d /var/lib/update-notifier ]; then touch /var/lib/update-notifier/dpkg-run-stamp; fi; if [ -e /var/lib/update-notifier/updates-available ]; then echo > /var/lib/update-notifier/updates-available; fi " } } }

if updates-available exists, it is cleared?!

**Comment by lutter** [comment]
This is just a test - they are run in the Augeas build process using augparse(1)

They don't influence how Augeas lenses behave - the test you quote simple checks that a certain string (in variable `complex_elem`) gets transformed into a certain tree (the stuff in the `{ ... }` notation)
