### ISSUE TITLE
sshd lens may be incorrect

### ISSUE THREAD

**Issue by trevor-vaughan** [hercules-team/augeas#205]
If you have an sshd_config file (as applied from the old, broken, version of the lens) that looks as follows:

Ciphers first
Ciphers second
Ciphers third

This is recognized as exactly the same match by the Puppet SSH provider as the following:

Ciphers first, second, third

However, the latter is correct.

I'm not sure if the fault lies in the lens or the SSH provider.

**Comment by raphink** [comment]
It's really hard currently to write a lens that will allow only one `Ciphers` entry in the file, anywhere. It has been attempted for the `Yum` module, but it generates very high complexity as it deals with combinatorics of the number of possible entries. Thus, we kind of have to support said syntax for now. It's up to the user of the lens to make use of it or not.

**Comment by trevor-vaughan** [comment]
Sorry, forgot to close this. An update to the lens on the main Augeas site seems to have fixed this issue.

**Comment by raphink** [comment]
Ah ok, thanks for closing.
