### ISSUE TITLE
sshd lense Multiple ListenAddress

### ISSUE THREAD

**Issue by tclavier** [hercules-team/augeas#206]
man sshd_config says it's possible to have multiple ListenAddress but 

    set /files/etc/ssh/sshd_config/ListenAddress/1 127.0.0.1

not work
and multiple 

    set /files/etc/ssh/sshd_config/ListenAddress IP

set only last.

**Comment by domcleal** [comment]
Can you expand on "not work" please?  Setting /1 will only set one address.  Set /2, /3 etc to add more.

**Comment by tclavier** [comment]
a sample it's more explicit :-)

```
$ grep Listen /etc/ssh/sshd_config
ListenAddress 192.168.33.11

$ augtool
augtool> set /files/etc/ssh/sshd_config/ListenAddress/1 127.0.0.1
augtool> set /files/etc/ssh/sshd_config/ListenAddress/2 192.168.33.11
augtool> save
error: Failed to execute command
```
After that, i make modification manually
```
# grep Listen /etc/ssh/sshd_config
ListenAddress 192.168.33.11
ListenAddress 127.0.0.1

$ augtool
augtool> get /files/etc/ssh/sshd_config/ListenAddress
error: Too many matches for path expression
There are 2 nodes matching /files/etc/ssh/sshd_config/ListenAddress
augtool> get /files/etc/ssh/sshd_config/ListenAddress/1
/files/etc/ssh/sshd_config/ListenAddress/1 (o)
```

**Comment by domcleal** [comment]
Ah, if you're creating multiple nodes then they'd be indexed - it wouldn't be additional nodes *beneath* the first.

    set /files/etc/ssh/sshd_config/ListenAddress[1] 127.0.0.1
    set /files/etc/ssh/sshd_config/ListenAddress[2] 192.168.33.11

By the way, when you get a save failure, run "print /augeas//error" (I think it says this) and when trying to show the layout, "print" is better than get as it's recursive.

**Comment by tclavier** [comment]
I close this issue, i just use bad syntax :

```
# augtool
augtool> set /files/etc/ssh/sshd_config/ListenAddress[1]/ 127.0.0.1
augtool> set /files/etc/ssh/sshd_config/ListenAddress[2]/ 192.168.33.11
augtool> save
Saved 1 file(s)

# grep Listen /etc/ssh/sshd_config
ListenAddress 127.0.0.1
ListenAddress 192.168.33.11
```

**Comment by tclavier** [comment]
thanks @domcleal, i just see your comment. 

Do you know why we must put 

    set /files/etc/ssh/sshd_config/ListenAddress[1] IP

and

    set /files/etc/ssh/sshd_config/AllowUsers/1 foo

**Comment by domcleal** [comment]
AllowUsers takes multiple arguments, which are split up (1, 2, 3 etc).  ListenAddress only takes one argument, so you need to create multiple settings for multiple values.
