### ISSUE TITLE
Web page about Hosts lens returns a 404 error

### ISSUE THREAD

**Issue by escrivio** [hercules-team/augeas#222]
Hello,

The link about Hosts lens is broken (404 error) : http://augeas.net/docs/references/lenses/files/hosts-aug.html .

Could the webmaster fix it please ? 

Thanking you for advance,

Regards,

Diego

**Comment by domcleal** [comment]
The module (lenses/hosts.aug) doesn't have any documentation unfortunately.  If you'd like to send a pull request to add some, it'd be much appreciated and would then be added to the website next time we generate it.

https://github.com/hercules-team/augeas-website/issues/5 is tracking this generally.
