### ISSUE TITLE
ssh "Match LocalPort": Augeas didn't load input

### ISSUE THREAD

**Issue by MelanieGault** [hercules-team/augeas#235]
Hi,

I have a simple ssh conf:
<pre>
AuthorizedKeysFile      .ssh/authorized_keys
Subsystem       sftp    /usr/libexec/openssh/sftp-server

Port 22
Port 6875
Match LocalPort 6875
   AllowUsers localise
   PermitRootLogin no
   PasswordAuthentication no
   PubkeyAuthentication yes
</pre>

I try to puppetize with hercules-team/augeasproviders_ssh puppet module.
I have errors on line 6:
<pre> Could not evaluate: Augeas didn't load /etc/ssh/sshd_config with Sshd.lns from /var/opt/lib/pe-puppet/lib/augeas/lenses: Get did not match entire input (line:6, character:0)
</pre>

Is 'Match LocalPort' supported ?
I don't really know augeas, but is there anything I can do to help havig this working ?

Thanks !
Mélanie.

(nearly same ticket submited in hercules-team/augeasproviders_ssh first https://github.com/hercules-team/augeasproviders_ssh/issues/10)

**Comment by raphink** [comment]
Hi,

This was reported by https://github.com/hercules-team/augeas/issues/75 and fixed as https://github.com/hercules-team/augeas/commit/1b299d58bbebd6551412bd721838e9e582a81a07.

The fix was released as part of Augeas 1.3.0.

**Comment by MelanieGault** [comment]
Hi,

thanks. I did not find this one...

Sorry for duplicating !
