### ISSUE TITLE
pam lens: arguments should be separated by spaces not tabs?

### ISSUE THREAD

**Issue by alexjfisher** [hercules-team/augeas#236]
augeasproviders_pam has made a horrible mess of my Oracle Linux files it touched.  Indentation is all over the place.

I think the problem is with the lens, but am not sure what the 'fix' might be.
Currently, the 'service', 'type', 'control', 'module-path' tokens *and* the arguments are all separated by tabs when a line is written by augeas.

I've compared various Ubuntu and OracleLinux pam.d files.
For the aforementioned tokens, sometimes they are tab separated and sometimes space separated.
However, the arguments always seem to be space separated. Should the lens be changed to mimic this?

What about the other whitespace?  Is there any way I can make this consistent across all entries in a pam.d file touched by augeas (with puppet)?

Many thanks,
Alex

**Comment by raphink** [comment]
I don't see a problem with changing the default to spaces instead of tabs for arguments. Defaults are always static though, they cannot be "guessed" from the current file.

**Comment by lorengordon** [comment]
I just ran into this as well. The pam.d(5) man page states: "The format of each rule is a space separated collection of tokens..." So it seems it would be more canonical to default to spaces for pam files. I'm happy to make this change and submit a PR, but this is my first time using augeas... Could you maybe point me to where to make this change in the lens, or wherever else? I'm reading over pam.aug and the augeas doc site, but it is non-obvious to this first-timer.

**Comment by raphink** [comment]
I'd welcome a PR. Spot `Util.del_ws_tab` in the lens and replace with `Sep.space` where it makes sense. Make sure tests pass (`augparse -I lenses/ lenses/tests/test_pam.aug`).

**Comment by lorengordon** [comment]
Found the docs on the Util functions. `Util.del_ws_spc` or `Util.del_ws " "` appear to be working. Is there a way to default to a separator token in a way that allows and a user to override it? Or perhaps a way to format the string such that it aligns the tokens to columns (this option would seem to be how the default pam files are structured).

**Comment by raphink** [comment]
No, there is no way to allow users to change the default at run time. `Util.del_*` functions are rather old, and I would prefer using `Sep.space` instead nowadays.

**Comment by lorengordon** [comment]
Got it. Found the docs for the `Sep` functions. I'll use those instead. Any thoughts on the failing tests in the PR, and how I can figure out exactly which test and assertion is failing?
