### ISSUE TITLE
rsyslog, support for filter conditions

### ISSUE THREAD

**Issue by drzraf** [hercules-team/augeas#238]
According to documentation:
http://www.rsyslog.com/doc/rsyslog_conf_filter.html
These stanzas are perfectly valid inside rsyslog.conf:
> :msg, contains, "blafoo" stop
or
> :msg, contains, "barbaz" ~
But are actually not supported by the rsyslog lense.

Syntax is 
> :property, [!]compare-operation, "value"

**Comment by raphink** [comment]
Property filters were added by ac21a022e4caede138f63dfe673cc1b1a88b542b and included since Augeas 1.3.0.

Support for the `~` action was added in 994e8bd57e9d0f7984e7a9727f5031615ba560e7 and not yet released.

**Comment by drzraf** [comment]
thank you!
