### ISSUE TITLE
Xml.lns is failing with complex attribute value

### ISSUE THREAD

**Issue by jairojunior** [hercules-team/augeas#253]
I'm trying to parse a WSO2 xml configuration file, but it's failing on line 253:

    <indexer class="org.wso2.carbon.governance.registry.extensions.indexers.RXTIndexer" mediaTypeRegEx="application/vnd.(.)+\+xml" profiles ="default,api-store,api-publisher"/>

`print /augeas//error` show me this:

/repository/conf/registry.xml/error = "parse_failed"
/repository/conf/registry.xml/error/pos = "12981"
/repository/conf/registry.xml/error/line = "253"
/repository/conf/registry.xml/error/char = "96"
/repository/conf/registry.xml/error/lens = "/usr/share/augeas/lenses/dist/xml.aug:153.10-155.60:"
/repository/conf/registry.xml/error/message = "Syntax error"

Any hints or help to fix this?

**Comment by raphink** [comment]
This was fixed in #145  and released as part of Augeas 1.3.0.
