### ISSUE TITLE
Sudoers lens doesn't support `!`

### ISSUE THREAD

**Issue by Karma-AK** [hercules-team/augeas#262]
Augeas Team,

Recently we got issues with sudoers lens (sudoers.aug) doesn't support the addition of a `!` used to negate values in a default /etc/sudoers file.
Eg: !DISALLOWED 
Throws out errors:
Debug: Augeas[includedirsudoers](provider=augeas): /augeas/files/etc/sudoers/error/message = Iterated lens matched less than it should 

As such, we can't proceed to use this lens which we need urgently. 
Please assist us with a solution/workaround asap as we suspect this could be a bug.

Thanks,
Anandk

**Comment by tpurkerson** [comment]
To add to this, using an exclamation mark in the /etc/sudoers file is pretty normal. The lens should be able to handle the following: 
`%sportshorseracingopssudoers ALL=(ALL) ALL, !DISALLOWED`

**Comment by raphink** [comment]
https://github.com/hercules-team/augeas/pull/263 intends to fix that, but still needs some improvements.

**Comment by AndrewWest** [comment]
hercules-team, when will this issue be resolved?

**Comment by raphink** [comment]
The fix was merged as 58a009f519778cc4810dbbcbe03657038bb7e6e1
