### ISSUE TITLE
Difficult with current API to insert node and refer to it afterwards

### ISSUE THREAD

**Issue by omgold** [hercules-team/augeas#285]
I believe I have a feature request for the API, except I missed some trick that can already do that.

What I want, is to insert a node at a specific location, like the 'insert' command does. But then I would like to refer to that node using a variable, like the 'defnode' command does. 

The problem arises, when one wants to insert nodes with bracketed indices []. In case one inserts a node before or after something else using insert, I have found no easy trick how to figure out what the bracketed index of the new node is.

So what I want is a variant of 'defnode' that allowed to specify the insert position like with 'insert'.

**Comment by raphink** [comment]
A few years ago, I proposed a feature for this:

https://fedorahosted.org/augeas/ticket/14

which was never implemented. I still believe this could be useful indeed.

**Comment by omgold** [comment]
What could also do the trick would be a combined rename/reorder. I mean a function that in one step renames a node and 'moves' it before or after another specified sibling. This would even be more flexible, as it could be used for other purposes, too.

**Comment by raphink** [comment]
There are `rename` and `move`/`mv` commands already.

**Comment by omgold** [comment]
Don't see how this helps. I understand move as moving a node to a different parent, not as reordering it before/after a specific sibling.

**Comment by omgold** [comment]
Ah, I believe I found a solution. The sequence

- insert (using unique label for new node)
- defvar
- rename

does the trick

**Comment by raphink** [comment]
What I do sometimes also is that I select the newly created node by the fact that it's the only one with no value/subnode in the tree.
