### ISSUE TITLE
NagiosCfg lens broken for /etc/nagios.cfg on Ubuntu 14.04 LTS due to spaces

### ISSUE THREAD

**Issue by poinck** [hercules-team/augeas#292]
On Ubuntu 14.04 LTS the NagiosConfig.lens has the same problem like described and solved with #177 .

I have reported a bug at Launchpad as well: https://bugs.launchpad.net/ubuntu/+source/augeas/+bug/1491406

**Comment by raphink** [comment]
That's because Ubuntu 14.04 uses an old version of Augeas (because it was released in April 2014 as its name suggests). I'd suggest you use the [Augeas PPA](https://launchpad.net/~raphink/+archive/ubuntu/augeas) to get version 1.4.0.
