### ISSUE TITLE
aug_save() fails with /augeas//errors pointing to multiple unrelated files

### ISSUE THREAD

**Issue by aniruddha-a** [hercules-team/augeas#308]
Hello,

I have been successfully using `augeas` with _Ubuntu 12.04_, to write `nameserver` entries to `/etc/resolv.conf`, when I moved to _Ubuntu 14.04_ (has `libaugeas.so.0.18.0`), I observed that `aug_save()` failed. I tried to debug by first installing `augeas-tools` and using the `augtool` CLI - that worked fine. But, programmatic editing and save still is erroring out!

when `aug_save()` failed, I tried to dump the `/augeas//error` as mentioned in the documentation:

    ret = aug_save(g_aug);
    if (ret != 0) {
        char **paths = NULL;
        int n = aug_match(g_aug, "/augeas//error", &paths);
        int i;
        const char *val;
        printf("\n ERR: match = %d\n", n);
        for (i = 0; i < n; i++) {
            printf("\n ERR: [%s]\n", paths[i]);
            aug_get(g_aug, paths[i], &val);
            printf("\n ERR: %s\n", val);
        }
        fflush(stdout);
    }

I see the following:

    ERR: match = 6
    ERR: [/augeas/files/etc/resolv.conf/error]
    ERR: clone_unlink_dst_augsave
    ERR: [/augeas/files/etc/dhcp/dhclient.conf/error]
    ERR: parse_failed
    ERR: [/augeas/files/etc/apt/apt.conf.d/01autoremove/error]
    ERR: parse_failed
    ERR: [/augeas/files/etc/rsyslog.conf/error]
    ERR: parse_failed
    ERR: [/augeas/files/etc/iproute2/rt_protos/error]
    ERR: parse_failed
    ERR: [/augeas/files/etc/iproute2/rt_dsfield/error]
    ERR: parse_failed

I am only making changes under the path `/files/etc/resolv.conf/`, I don't know why all these _other paths_ are even appearing in the error list (I assume that the error dumping code is correct)
(the binary is run with privileges [`sudo`])
Any pointers to debug further?
Can I _restrict_ the save to only `/files/etc/resolv.conf/` path ?

Thanks.

**Comment by domcleal** [comment]
The other files aren't being *saved*, they're reporting parse errors which will have happened at startup (as Augeas loads a set of default modules and files automatically).

You can safely ignore those errors - Augeas isn't changing the files.  Alternatively, you can pass the AUG_NO_MODL_AUTOLOAD flag into aug_init to disable autoloading, and then use either aug_transform or editing of /augeas/load to set up the module and paths you want to load, then call aug_load.

**Comment by aniruddha-a** [comment]
Thanks. Is there any way I can _clear_ those startup parse errors ?

**Comment by aniruddha-a** [comment]
I did the following:

Immediately after `aug_init()`, I cleared the errors with `aug_rm(aug, "/augeas//error")`
But still I am unable to _save_  entry to `/etc/resolv.conf`, I get:

    /augeas/files/etc/resolv.conf/error = clone_unlink_dst_augsave
    /augeas/files/etc/resolv.conf/error/message = No such file or directory

i.e, `aug_save()` returns `-1`

I can ignore the errors as long as I can save the entries to `/etc/resolv.conf` !

Also IIUC, the path `/files/etc/resolv.conf` refers to the actual file path (that I am editing)
and ` /augeas/files/etc/resolv.conf` is for the meta-information maintained by Augeas for that file/lens - is that correct ? in which case what does error in that path supposed to mean ?

Thanks.

**Comment by domcleal** [comment]
> But still I am unable to save entry to /etc/resolv.conf, I get:
> 
> /augeas/files/etc/resolv.conf/error = clone_unlink_dst_augsave
> /augeas/files/etc/resolv.conf/error/message = No such file or directory
> 
> i.e, aug_save() returns -1

This probably means that /etc/resolv.conf isn't writable in some way.  Usually it means that it can't be renamed or unlinked - check that you're running Augeas as root, and that the file isn't actually a bind mount.

> Also IIUC, the path /files/etc/resolv.conf refers to the actual file path (that I am editing)
> and /augeas/files/etc/resolv.conf is for the meta-information maintained by Augeas for that file/lens - is that correct ?

Exactly right.

**Comment by aniruddha-a** [comment]
Thanks Dominic.
I'm not sure, but I think it could be _bind_ mount (I tried a small program and `rename()` did fail). I am running Augeas from a _SUID_ program, so privileges should not be a problem. But how is it, that `augtool` is able to save the file ? but I am unable to :-/

**Comment by aniruddha-a** [comment]
For now, I am going with the following approach:

-  set `/augeas/save`  = `newfile`
-  `aug_save()` writes to `/etc/resolv.conf.augnew`
-  copy [contents of] `/etc/resolv.conf.augnew` to `/run/resolvconf/resolv.conf`
