### ISSUE TITLE
Httpd.lns cannot parse file without ending EOL

### ISSUE THREAD

**Issue by domcleal** [hercules-team/augeas#312]
Httpd.lns cannot parse a file that's missing an EOL on the last line:

<pre>
$ echo -n > /tmp/test.conf
$ augcheck /tmp/test.conf Httpd
/tmp/augcheck.FlO5pO/parse_file.aug:3.0-.55:exception thrown in test
/tmp/augcheck.FlO5pO/parse_file.aug:3.5-.51:exception: Syntax error
    Lens: /usr/share/augeas/lenses/dist/httpd.aug:98.10-.44:
    Error encountered at 1:0 (0 characters into string)
                               <|=|>                           

    Tree generated so far:
    

Syntax error in lens definition
Failed to load /tmp/augcheck.FlO5pO/parse_file.aug
$ echo > /tmp/test.conf
$ augcheck /tmp/test.conf Httpd
Test result: /tmp/augcheck.UvJNvV/parse_file.aug:3.0-.55:
  {  }
</pre>

**Comment by lutter** [comment]
What does `augcheck` do ? Does that call augparse ?

There's a subtle difference between how augparse and augtool work: when you write `test lns get s` for some string `s`, the lens gets applied to exactly that string. When augtool loads a file, it actually checks whether that file ends in a newline, and adds one if it doesn't, as it is so common for lenses to assume that a file ends with a newline, but actual files to not do that.

**Comment by domcleal** [comment]
> What does augcheck do ? Does that call augparse ?

Ah yes, one of @raphink's useful utilities: https://github.com/raphink/augeas-sandbox/blob/master/augcheck

I see what you mean about the newline now, it seems to work fine in practice.  Thanks!

**Comment by lutter** [comment]
Nice .. I had no idea that those existed; with @raphink's work on Lua integration, would we port them to Lua and include them in the main augeas repo ?

**Comment by raphink** [comment]
That could be an option @lutter, it shouldn't be too hard indeed.
