### ISSUE TITLE
RPM versions available through repos..

### ISSUE THREAD

**Issue by schplat** [hercules-team/augeas#314]
So, I need functionality that was added into the 1.2.0 release.  The RPM versions available are really odd.

On RHEL5, I can get augeas 1.2.0 through EPEL..
On RHEL6, I can get augeas 1.0.0 through the base rhel6 repo.
On RHEL7, I can get augeas 1.1.0 through the base rhel7 repo.

Why does RHEL5 offer a newer version than newer OS releases?  Are there any plans to fix this?  Or is there another repo that can be used?  Or am I on my own for building and distributing my own RPMs on this one?

**Comment by domcleal** [comment]
> Why does RHEL5 offer a newer version than newer OS releases? Are there any plans to fix this?

That was my fault, I didn't really think it through when I updated EPEL5.  I should have kept it at 1.0.0 I suppose.  I don't plan on reverting it, if that's what you mean, it's be messy (epoch and perhaps break things for people).

> Or is there another repo that can be used? Or am I on my own for building and distributing my own RPMs on this one?

The project doesn't provide one, but it is trivial to rebuild the SRPMs if you want to do so.  I maintain the RHEL version now and welcome bug or feature reports in Bugzilla (or via support if you're a customer), but these things don't move very quickly.

The EL7 version is being updated to 1.4.0 in 7.2, you can find preview packages linked from here: https://www.redhat.com/archives/augeas-devel/2015-June/msg00006.html.  Rebases are rare though and may not happen again in 7.

**Comment by schplat** [comment]
Trivial yes, but more overhead as well.  And we're still moving all of our production stuff off of Cent 5, Cent 7 is a pipe dream at this point..

The fix I'm looking for is:

Yum: [...] Split excludes as lists, bug #275

As I'm looking to make puppet manage yum excludes, and this hasn't been backported as of yet.  I may just be able to move the yum lens from 1.4.0 into /usr/share/augeas/dist and work with it that way.

But thank you for the response, at least I know what direction I'll need to move in.

Thanks.

**Comment by domcleal** [comment]
> I may just be able to move the yum lens from 1.4.0 into /usr/share/augeas/dist and work with it that way.

Use /usr/share/augeas/ if you're going to do this, it'll take priority over dist/, which is intended for the package itself.  You may find some lenses need updated versions of utilities, or more care when backporting.



> The fix I'm looking for is:
> 
> Yum: [...] Split excludes as lists, bug #275
> 
> As I'm looking to make puppet manage yum excludes, and this hasn't been backported as of yet.

Yeah, I avoid making incompatible tree changes in backports - useful as they are - because it can unexpectedly break an entire estate's Puppet manifests or something.
