### ISSUE TITLE
Escaped dots in regexps crashing the httpd lens

### ISSUE THREAD

**Issue by pde** [hercules-team/augeas#324]
I still see augeas parser crashes with this file:

https://github.com/letsencrypt/letsencrypt/files/36394/htaccess.txt

**Comment by pde** [comment]
The lines in question appear to be these two:
```
    RewriteRule \.css\.gz$ - [T=text/css,E=no-gzip:1]
    RewriteRule \.js\.gz$ - [T=text/javascript,E=no-gzip:1]
```
I think the escaped dots are the problem.

**Comment by domcleal** [comment]
Yes, you're right, it is those lines.  The last change I made didn't permit the backslash at the start of the argument, but that wasn't necessary - it just has to be prevented from being the last character (to prevent an ambiguity in the lens).  The PR at #325 now allows the argument to start with a backslash and seems to parse that file for me.
