### ISSUE TITLE
httpd lens fails on missing double quote to end directive argument

### ISSUE THREAD

**Issue by domcleal** [hercules-team/augeas#330]
The SSLCipherSuite directive here is missing an ending double quote, but Apache appears to parse it fine (it passes a config test anyway).

<pre>
	SSLProtocol all -SSLv2 -SSLv3
        SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRS$
        SSLCertificateFile /etc/ssl/certs/example.com.crt
</pre>

(from https://gist.github.com/hokascha/87da802584fa2b0675cc)

**Comment by domcleal** [comment]
Another valid example:

<pre>
# Force simple error message for requests for non-existent favicon.ico.
<Files favicon.ico>
  # There is no end quote below, for compatibility with Apache 1.3.
  ErrorDocument 404 "The requested file favicon.ico was not found.
</Files>
</pre>

(from http://cgit.drupalcode.org/drupal/tree/.htaccess?h=6.37, https://github.com/letsencrypt/letsencrypt/issues/1531#issuecomment-163540310)

**Comment by kristofferwiklund** [comment]
As describe in this Drupal issue: https://www.drupal.org/node/281131#comment-918939

Apache 1.3 according to http://httpd.apache.org/docs/1.3/mod/core.html#errordocument
"Messages in this context begin with a single double-quote character (")"

Apache 2.0 according to http://httpd.apache.org/docs/2.0/mod/core.html#errordocument
"Prior to version 2.0, messages were indicated by prefixing them with a single unmatched double quote character."
