### ISSUE TITLE
Cannot install 1.4 from the PPA due to build errors

### ISSUE THREAD

**Issue by thedrow** [hercules-team/augeas#336]
See https://launchpadlibrarian.net/208252496/buildlog_ubuntu-wily-amd64.augeas_1.4.0-0ubuntu1~augeas1_BUILDING.txt.gz

**Comment by thedrow** [comment]
@raphink You maintain that PPA right? Care to take a look?

**Comment by raphink** [comment]
Yes, I am aware of this, but didn't have the time to look it up. Interestingly, it failed to build in amd64 only.

**Comment by domcleal** [comment]
It looks like the build is under the root account.  You might be hitting a bug I've seen reported against the RPM where a test in test-save fails when run as root:

<pre>
FAIL: test-save
===============
pending (testRemoveNoPermission): can't test permissions under root account
F...........
There was 1 failure:
1) testSaveNoPermission:
test-save.c:372: expected <-1> but was <0>
!!!FAILURES!!!
Runs: 12 Passes: 11 Fails: 1
</pre>

(from the RPM build)

Hard to say for certain without the test suite log that it's the same thing, but I was going to fix that soon by adding a uid check (similar to some other tests we skip when uid()==0).

**Comment by raphink** [comment]
Ah, interesting, although I wonder why it would pass with the i386 builder.

**Comment by raphink** [comment]
I'm testing in a wily docker environment right now, to get access to the logs.

**Comment by thedrow** [comment]
I need to able to install 1.4 as soon as possible. Let me know if I can help.

**Comment by raphink** [comment]
@thedrow you could always try the vivid binary, it's likely to work.

**Comment by thedrow** [comment]
I guess that's true. Thanks.

**Comment by raphink** [comment]
@domcleal confirmed:

```
FAIL: test-save
===============

pending (testRemoveNoPermission): can't test permissions under root account
F...........

There was 1 failure:
1) testSaveNoPermission:
test-save.c:372: expected <-1> but was <0>
```

How did you fix it? Patching this test?

**Comment by domcleal** [comment]
I ignored it, but I did just write https://github.com/domcleal/augeas/commit/592f9cff0989f308f52daa8009900181fd69cf20 which I'll push to master once it's passed on Travis.

**Comment by raphink** [comment]
How so you ignored it? You ignored the tests passing?

**Comment by domcleal** [comment]
I mean ignored the bug report, as RPMs shouldn't ever be built as root :)

**Comment by raphink** [comment]
Hehe, unfortunately, it seems the Ubuntu builders run as root (or at least fakeroot), so I'll have to fix that anyway.

**Comment by domcleal** [comment]
Yeah, just add that commit above to your patch set and it should skip over it.

**Comment by domcleal** [comment]
Fixed in https://github.com/hercules-team/augeas/commit/2d094e3a00e7f90b3d941cd56b381db729e61f88

**Comment by thedrow** [comment]
Can you guys please trigger a build/retag 1,4?

**Comment by raphink** [comment]
Uploading now for wily with the patch.

**Comment by thedrow** [comment]
Thanks!

**Comment by raphink** [comment]
https://launchpad.net/~raphink/+archive/ubuntu/augeas/+build/8452102

**Comment by raphink** [comment]
You're welcome to test if you have Wily machines.

**Comment by raphink** [comment]
And I will test and upload for Xenial, too while I'm at it. Hopefully, 1.5 can be released for Xenial.

**Comment by thedrow** [comment]
It's unpublished yet. Should I simply download the deb file?

**Comment by raphink** [comment]
Should be published very soon I think.

**Comment by thedrow** [comment]
Seems like it works. Thanks a lot!
