### ISSUE TITLE
Allow to parse files in arbitrary paths

### ISSUE THREAD

**Issue by thedrow** [hercules-team/augeas#337]
Sometimes, configuration is not located in the default locations specified in the lenses files.
It be great if we could just point augtool to a file, specify the lens required to parse it and get the tree despite the fact that it's not placed in one of the included locations.

**Comment by domcleal** [comment]
`augtool --transform 'Httpd incl /etc/foo.conf'` or similar.  When using the API, you can call aug_transform or edit /augeas/load and call aug_load.

**Comment by thedrow** [comment]
Oh, thanks!
We really need better documentation.
Where do I add this to?

**Comment by domcleal** [comment]
Possibly the quick tour or FAQ on the website?  https://github.com/hercules-team/augeas-website/tree/master/pages
