### ISSUE TITLE
Please use github.com/coreutils/gnulib

### ISSUE THREAD

**Issue by szepeviktor** [hercules-team/augeas#345]
Please change your submodule's URL
https://github.com/coreutils/gnulib.git

**Comment by lutter** [comment]
Why ?

**Comment by szepeviktor** [comment]
Now it cannot be browsed on GitHub.

**Comment by lutter** [comment]
The FSF hosts its projects on Savannah, not on Github. You can find details of gnulib at http://savannah.gnu.org/projects/gnulib As that is the official upstream location, we will continue pointing to that.

**Comment by szepeviktor** [comment]
OK

**Comment by szepeviktor** [comment]
Please consider putting a link into README
https://github.com/coreutils/gnulib
