### ISSUE TITLE
Commenting out a line

### ISSUE THREAD

**Issue by szepeviktor** [hercules-team/augeas#355]
Good morning team!

I am trying to convert a chrony config line into a comment
`<LABEL> = <VALUE>` → `#comment[] = <LABEL> <VALUE>`

It would be possible by inserting a node before the line then renaming it to a comment. The only thing I am not able to do is concatenating label and value.
Please advise.
Thanks!

**Comment by raphink** [comment]
There is currently no way to do that natively using the augeas API. I'd advise simply using whichever language you fancy with the corresponding augeas bindings, and performing the concatenation in that language.

**Comment by szepeviktor** [comment]
Thank you.

Is there any other python example than [the test](https://github.com/hercules-team/python-augeas/blob/master/test/test_augeas.py)?

**Comment by raphink** [comment]
Ansible and salt both have augeas support, coded in python.
