### ISSUE TITLE
Unable to load single lens

### ISSUE THREAD

**Issue by aniruddha-a** [hercules-team/augeas#360]
Hello,

I want to be able to load a single lens, I first wanted to try with `augtool`, so that later
I can do the same in my `C` code. Somehow this doesn't seem to work! I tried the lens name as well as `@<Module>` notation.

```
# augtool --noautoload
augtool> set /augeas/load/Interfaces/lens "interfaces.aug"
augtool> set /augeas/load/Interfaces/incl "/etc/network/interfaces"
augtool> load
error: Lens not found
Can not find lens interfaces.aug

```

```
# augtool --noautoload
augtool> set /augeas/load/Interfaces/lens "@Interfaces"
augtool> set /augeas/load/Interfaces/incl "/etc/network/interfaces"
augtool> load
error: Lens not found
Could not find module Interfaces
```

Will it not automatically search the `AUGEAS_LENS_LIB` paths ?

**Comment by domcleal** [comment]
> augtool> set /augeas/load/Interfaces/lens "interfaces.aug"

Use `Interfaces.lns` which is the name of the lens inside the module file.

You can also use `augtool --transform 'Interfaces incl /etc/network/interfaces'` or `aug_transform(aug, "Interfaces", "/etc/network/interfaces", 0);`.

**Comment by raphink** [comment]
To complete @domcleal's answer:

- `interfaces.aug` is not the lens name, it's the module filename for the `Interfaces` module
- the Interfaces modules has several lenses, and the standard/public one is `Interfaces.lns`
- the `@Module` notation only works for autoloading, not for manual loading

**Comment by aniruddha-a** [comment]
Thanks Dominic and Raphael. I get the distinction now, however I am not sure how I can figure out the name of the public lens from the module.

I am now doing the following:

```
aug = aug_init("/", LENS_PATH, AUG_SAVE_BACKUP  | AUG_NO_ERR_CLOSE |                                  AUG_NO_MODL_AUTOLOAD);
// ...
aug_set(aug, "/augeas/load/Interfaces/lens", "Interfaces.lns");
aug_set(aug, "/augeas/load/Interfaces/incl", "/etc/network/interfaces");
aug_load(aug);

```
And its working.

**Comment by domcleal** [comment]
> however I am not sure how I can figure out the name of the public lens from the module.

99% of modules use "lns" as the public lens, though some like IniFile have more available.  You'll have to read the documentation, either near the top or near each lens (`let X`).

Modules that load by default will have a pair of lines, usually: `autoload xfm` and `let xfm` and the latter will then reference the public lens (`transform lns filter`, where `lns` is the lens name).
