### ISSUE TITLE
Hjson Lens

### ISSUE THREAD

**Issue by laktak** [hercules-team/augeas#365]
Is anyone willing to write a [Hjson](http://hjson.org) lens for Augeas?

I took a look at the JSON lens but it uses some features that are not suitable for Hjson.

For example keys and strings can be quoteless unless they start with a JSON control character:

```
{
   foo: bar
}
```

so after `set /files/../test.hjson/dict/entry[1]/string {}` the lens would need to save it as

```
{
   foo: "{}"
}
```

Is this possible/supported?

**Comment by raphink** [comment]
I'm not interested in writing it (I personally think HOCON & HJson are bad ideas), but if you write the lens, I'm willing to merge it.

**Comment by laktak** [comment]
Why? If you'd care to explain you can find me on [twitter](https://twitter.com/laktakk).

As for my question - is it even possible?

**Comment by raphink** [comment]
I think it should be possible. That said, I give up on hocon, as it comes down to writing a parser for a language (just as toml BTW).

As for why: https://xkcd.com/927/

There's enough (complex) formats for config files imo (just look at all these lenses already!) without adding new even more complex, typed, ones.

**Comment by laktak** [comment]
Thanks for the info.

A lot of people are using JSON for configs. I think that's not the right tool for the job. That's also the reason for Hjson.

**Comment by raphink** [comment]
The main point of json is that it's a standard serialisation format, that if native to JavaScript and hence allows to easily create web interfaces. So I'm not convinced of the usefulness of a json format that is not JavaScript compliant.

**Comment by raphink** [comment]
Also, json being a serialisation format (much like yaml, of which it is a valid subset), it is not meant for configurations. Personally, after writing quite a few augeas lenses in the last 8 years, I usually prefer to use some kind of inifile format (but not toml, which I find too complex), or just shellvar if key/values are sufficient. Typed formats such as hocon or Erlang hashes definitely cause more problems than they solve imo (I also say this from having spent the last years maintaining and contributing to puppet modules with very complex templates for such formats).

**Comment by lutter** [comment]
Hi Christian,

On Tue, Apr 19, 2016 at 1:59 AM, Christian Zangl <notifications@github.com>
wrote:

> Is anyone willing to write a Hjson <http://hjson.org> lens for Augeas?
>
> I took a look at the JSON lens but it uses some features that are not
> suitable for Hjson.
>
> For example keys and strings can be quoteless unless they start with a
> JSON control character:
>
> {
>    foo: bar
> }
>
> so after set /files/../test.hjson/dict/entry[1]/string {} the lens would
> need to save it as
>
> {
>    foo: "{}"
> }
>
> Is this possible/supported?
>

It's possible, the details of how that would be done depend a lot on what
the rest of the Hjson grammar looks like. Is there a formal grammar for it
? That sort of thing makes it generally easier to write an Augeas lens. I
won't have time to write one, but would be more than happy to merge one. This
page
<https://github.com/hercules-team/augeas/wiki/Creating-a-lens-step-by-step>
has some docs around what exactly is involved with doing that.

David

**Comment by laktak** [comment]
> json format that is not JavaScript compliant.

JSON is not JavaScript - see [hjson.org](http://hjson.org)

> Also, json being a serialisation format (much like yaml, of which it is a valid subset), it is not meant for configurations.

totally agree

**Comment by laktak** [comment]
> It's possible, the details of how that would be done depend a lot on what the rest of the Hjson grammar looks like. Is there a formal grammar for it ? That sort of thing makes it generally easier to write an Augeas lens. I won't have time to write one, but would be more than happy to merge one. This page <https://github.com/hercules-team/augeas/wiki/Creating-a-lens-step-by-step> has some docs around what exactly is involved with doing that.

Thanks. Maybe someone with some Augeas experience will give it a try now that the [SABNF](https://github.com/ldthomas/apg-js2/blob/master/SABNF.md) grammar can be found [here](https://github.com/laktak/hjson/tree/master/rfc)?
