### ISSUE TITLE
Link to Stock Lens Hosts not working

### ISSUE THREAD

**Issue by TimoKramer** [hercules-team/augeas#373]
Hi
I tried to read the Doc for your Host-lens at http://augeas.net/docs/references/1.4.0/lenses/files/hosts-aug.html but I cannot open it.
Regards

Timo

**Comment by domcleal** [comment]
The module has no documentation (https://github.com/hercules-team/augeas/blob/master/lenses/hosts.aug), so the page is missing.

Sorry!  (Tracked under https://github.com/hercules-team/augeas-website/issues/5.)
