### ISSUE TITLE
Allow to build without libxml2

### ISSUE THREAD

**Issue by thedrow** [hercules-team/augeas#382]
When linking to libaugeas in Linux it requires the application to link with libxml2 which may or may not require linking with iconv and libz, depending on how you build it.
On Ubuntu libxml2 is linked with iconv.
Can we introduce a build option to build libaugeas without libxml2? Is that even possible?

**Comment by raphink** [comment]
That could be interesting indeed. It would probably require to adapt the `configure.ac` file.

**Comment by thedrow** [comment]
Which is something I'm not very familiar with.
If this were CMake I'd submit a PR.
Care to take a look please?

**Comment by lutter** [comment]
This would require quite a bit of surgery; I am not quite sure what we should do at the API level. The two options I can see are

- remove aug_to_xml from the API completely if augeas is built without libxml
- replace the implementation of aug_to_xml with a noop version that always returns an error

If we do the former, any code that wants to use aug_to_xml would file during compilation; with the latter, compilation would succeed but code that uses aug_to_xml would always produce a runtime error.

Before we go there, I'd like to better understand the reasons for compiling without libxml - at least on my Fedora machine, trying to remove libxml2 removes so many packages that I think the system would be unusable afterwards. Some of these are gnome-shell, libvirt/qemu, kernel-tools, and java-1.8.0-openjdk - is the situation on Ubuntu different ?

**Comment by thedrow** [comment]
I'm not suggesting to remove libxml2 completely. I'm suggesting that when linking with libaugeas as a library we'd not link with libxml2 functionality unless it's necessary.

We can, alternatively provide the API in a different so/a library. Yes that would break the API/ABI but it will be an explicit change that is easy to fix.

**Comment by lutter** [comment]
What I was saying was that to make it possible to not link against libxml2, we'd need to add a `--without-libxml` option to the `configure` script. My previous comment was about how augeas built with and without libxml support should behave.

Can you explain a bit more why you think building without libxml would be useful ?

**Comment by thedrow** [comment]
Because at least on Ubuntu linking with libaugeas requires me to link with both libxml2 and iconv.
It complicates the dependency chain and if I don't need xml functionality it's just work I don't need to do.

**Comment by lutter** [comment]
Are you linking statically or dynamically ? Either way, `pkg-config` should produce the correct linker flags by either running `pkg-config --libs augeas` or `pkg-config --libs --static augeas`. If not, the augeas.pc file on Ubuntu might need to be adjusted.

**Comment by thedrow** [comment]
I don't think the libaugeas-dev package has pkg-config on Ubuntu. I'll check again.
Also, I'm using CMake which requires a bit of it's own voodoo to find the library using pkg-config. As far as I've seen it doesn't find the dependent libraries as well.

I'm linking statically.

**Comment by lutter** [comment]
If the Ubuntu package does not install the right pkg-config file, you should discuss that with the Ubuntu packager. Augeas does ship with the correct augeas.pc as far as I can tell.

**Comment by raphink** [comment]
Ubuntu packager here.

```shell
$ dpkg -L libaugeas-dev | grep augeas.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/augeas.pc
```

That should do, shouldn't it?

**Comment by thedrow** [comment]
It should but it doesn't. At least not when you use CMake. I don't know why but CMake didn't link with iconv.
In any case, I still think that if you don't need XML output, you shouldn't require it as a dependency.
Make it optional either by moving it to another .a/.so or by allowing to build without it.

**Comment by lutter** [comment]
I don't know enough about CMake to help you figure out what exactly needs to be done to statically link against libaugeas.  Since habving libxml2 installed is pretty much a required part of any Linux machine, and that making it optional to link against it would be quite a bit of work, I am closing this issue.
