### ISSUE TITLE
Shellvars seems to fail when a '.' is used in the key.

### ISSUE THREAD

**Issue by xaque208** [hercules-team/augeas#383]
Using the Puppet provider setting values in /boot/loader.conf may contain boot time sysctl options such as `kern.geom.label.gptid.enable="0"`.  Using shellvar type (implementing the Shellvars lense) with puppet fails either reading or writing the augeas tree when the key has a '.' in the name.

**Comment by lutter** [comment]
Hey Zach, could you attach a simple example of a file where this fails ? Much easier to fix it with that in hand.

**Comment by raphink** [comment]
`kern.geom.label.gptid.enable="0"` is not valid Shellvar syntax:

```shell
$ kern.geom.label.gptid.enable="0"
kern.geom.label.gptid.enable=0: command not found
```

You need to use another lens for that file.

**Comment by xaque208** [comment]
@raphink Makes perfect sense why it doesn't work then.  I'll have a look at the other lenses to see what else might apply.  Thank you.
