### ISSUE TITLE
Puppetfile lens can't parse "mod 'puppetlabs/apache', :latest"

### ISSUE THREAD

**Issue by mchouque** [hercules-team/augeas#427]
Hello,

A module can be described as (cf https://docs.puppet.com/pe/latest/cmgmt_puppetfile.html) :
```
mod 'puppetlabs/apache', :latest
```

The problem I have is the portion of code in the lens which matches the version doesn't allow anything like that (colons are excluded from the match): 
```
let version = [ label "@version" . Quote.do_quote (store /[^:\n]+/) ]
```

It doesn't match either the opts because they are of the form "key => value":
```
let opt = [ Util.del_str ":" . key Rx.word . del /[ \t]*=>[ \t]*/ " => "
               . Quote.do_quote (store /[^,\n]*/) ]
```

I tried the following and it works but given it's my first time dealing with augeas, I don't find that really clean nor do I know if it's the best way (not sure how to best "match" latest):
```
let version = [ label "@version" . (Quote.do_quote (store /[^:\n]+/) | 
               (Util.del_str ":" . store /latest/)) ]
```

Any help would be appreciated, I'd have no problem creating a merge request to fix that.

Cheers,
Mathieu

**Comment by mchouque** [comment]
What I propose doesn't really work. It not only messes by transforming :latest to latest but also when you save a file, what was once:
````
mod 'puppetlabs/apache', :latest
````

becomes
```
mod 'puppetlabs/apache', "latest"
````

Clearly not what we want, back to the drawing board...

**Comment by mchouque** [comment]
Alright so what I offered didn't work: it couldn't properly save or read a modified Puppetfile. What seems to be working is this:
let mod_version = /[A-Za-z0-9_.-]+/
  in let version = [ label "@version" . Quote.do_quote_opt (store mod_version) ] | [ label "@version" . store /:latest/ ]

**Comment by vchepkov** [comment]
That's been awhile since this ticket has been opened

The syntax of Puppetfile allows multiple symbols, which are not recognized by the lens.

For example:
```
mod 'data',
  :git    => 'ssh://git@stash.example.com/bp/puppet-hiera.git',
  :branch => :control_branch,
  :default_branch => 'development',
  :install_path   => '.'
```

**Comment by raphink** [comment]
I'm sorry I didn't follow this issue. My suggestion to fix the initial problem is to make option values optional:

```diff
-  in let opt = [ Util.del_str ":" . key Rx.word . del /[ \t]*=>[ \t]*/ " => "
-               . Quote.do_quote (store /[^,\n]*/) ]
+  in let opt = [ Util.del_str ":" . key Rx.word . (del /[ \t]*=>[ \t]*/ " => "
+               . Quote.do_quote (store /[^,\n]*/))? ]
```

This successfully parses `:latest` as:

```
  { "1" = "puppetlabs/apache"
    { "latest" }
  }
```
