### ISSUE TITLE
augtool: out-of-memory

### ISSUE THREAD

**Issue by joerg-krause** [hercules-team/augeas#438]
I've cross-compiled *augeas* for an ARMv5 platform with 64MB RAM. When running the *augtool* the free memory rapidly decrease from about 35MB to 0MB within a few seconds and Linux crashs with a out-of-memory message.

Is *augtool* that hungry?

**Comment by domcleal** [comment]
That seems about right for the default configuration, which loads nearly 200 modules. If you load a more minimal set of modules (e.g. augtool -A, then add what you need) then it should be much lower.

**Comment by joerg-krause** [comment]
You're right! `augtool -A` works. The memory consumption is now something over 100KB. Thanks!
