### ISSUE TITLE
Allow underscores in postfix_virtual

### ISSUE THREAD

**Issue by lingfish** [hercules-team/augeas#439]
As far as I can tell, this is legal in an e-mail address; postfix accepts it fine.

Similiar to https://github.com/hercules-team/augeas/commit/c3c7bfa8f7b042be417b39889187c8b37b3297ee, all that is needed is:

```
--- /usr/share/augeas/lenses/dist/postfix_virtual.aug.ORIG      2016-01-05 10:02:36.000000000 +1100
+++ /usr/share/augeas/lenses/dist/postfix_virtual.aug   2017-02-14 12:37:34.024967401 +1100
@@ -32,7 +32,7 @@
   del (space_or_eol_re? . sep . space_or_eol_re?) default

 (* View: word *)
-let word = store /[A-Za-z0-9@\*.+=-]+/
+let word = store /[A-Za-z0-9@\*.+=-_]+/

 (* View: comma *)
 let comma = space_or_eol "," ", "

```

**Comment by domcleal** [comment]
If you can open that as a pull request then we'd be happy to merge it. A bonus would be a small example also added to lenses/tests/test_postfix_virtual.aug.

**Comment by lingfish** [comment]
You're right... I tried to sneak a lazy through ;)  Done.
