### ISSUE TITLE
How to parse /etc/postfix/aliases

### ISSUE THREAD

**Issue by ioquatix** [hercules-team/augeas#447]
I tried using 

```
transform Aliases incl /etc/postfix/aliases
load
```
but still

```
print /files/etc/aliases
```

is empty.

What am I doing wrong?

**Comment by domcleal** [comment]
> print /files/etc/aliases

Surely that should be: `/files/etc/postfix/aliases`?

Else run `errors` to print any parse errors.

**Comment by ioquatix** [comment]
> Surely that should be: /files/etc/postfix/aliases?

Ah, okay, I might have done thew wrong thing then :D

**Comment by domcleal** [comment]
Closing, please re-open if that wasn't it.

**Comment by ioquatix** [comment]
Thanks.
