### ISSUE TITLE
Inserting label to collection of keys is wrongly escaped

### ISSUE THREAD

**Issue by jreidinger** [hercules-team/augeas#451]
Easy way how to reproduce problem:

```
jreidinger@pepa:/tmp> cat /tmp/zypp.conf 
# test
# test2
```

```
jreidinger@pepa:/tmp> augtool -t 'Puppet incl /tmp/zypp.conf'augtool> match /files/tmp/zypp.conf/*
/files/tmp/zypp.conf/#comment[1] = test
/files/tmp/zypp.conf/#comment[2] = test2  
augtool> ins #comment[3] after /files/tmp/zypp.conf/#comment[1]
augtool> match /files/tmp/zypp.conf/*
/files/tmp/zypp.conf/#comment[1] = test
/files/tmp/zypp.conf/#comment\[3\] = (none)
/files/tmp/zypp.conf/#comment[2] = test2
augtool> quit
```

see wrong format of `#comment[3]` which cause failure during saving.

it affects only insert, set is not affected.

If you need more info or if I do something wrong, then I would welcome any help. I need this insert to place comment to place I want.

**Comment by domcleal** [comment]
`ins #comment[3] after ...` should simply be `ins #comment after ...`, as `#comment` is the node name. The `[3]` or `[1]` is the index so you can refer to them uniquely in a path, it isn't actually part of the name.

If you're trying to add a comment in between the two, then `ins #comment after /files/tmp/zypp.conf/#comment[1]` will mean you have:

    /files/tmp/zypp.conf/#comment[1] = test
    /files/tmp/zypp.conf/#comment[2] = (none)
    /files/tmp/zypp.conf/#comment[3] = test2

i.e. the index changes as what was the second `#comment` node is now the third, then you can reference `/files/tmp/zypp.conf/#comment[2]` for the new node.

**Comment by jreidinger** [comment]
@domcleal thanks for response and help. I miss it in documentation.
