### ISSUE TITLE
Change filter for rsyslog.aug lens

### ISSUE THREAD

**Issue by dallendoug** [hercules-team/augeas#465]
I'm coming at this from the use of augeas in osquery, so forgive me if I am asking something out of bounds here, or this is not a proper use case for normal augeas use.

I want to be able to use the rsyslog.aug lens against the configuration files that are in /etc/rsyslog.d/ as well (e.g. /etc/rsyslog.d/50-default.conf on Ubuntu 16). Could the filter for this lens just be changed from

```
let filter = incl "/etc/rsyslog.conf"
```

to 

```
let filter = incl "/etc/rsyslog.conf"
           . incl "/etc/rsyslog.d/*"
           . Util.stdexcl
```

This seems to be the paradigm for several other lenses that need to look at a directory of config files as well as the base config. This achieves what I need (for now), but I didn't know if there was more involved before submitting the PR, or if this should actually have a new lens created for it.

So I'm asking here, rather than just submitting the PR without preamble. TIA.

**Comment by domcleal** [comment]
Sure, that's fine. Please open a PR with the change you suggested, that's all that's necessary.

**Comment by dallendoug** [comment]
Looks like this was accepted! https://github.com/hercules-team/augeas/pull/475 -- thanks!

I will close the issue.
