### ISSUE TITLE
fails to parse latest java8u131 java.security file

### ISSUE THREAD

**Issue by qs5779** [hercules-team/augeas#468]
[java8u131_java.security.txt](https://github.com/hercules-team/augeas/files/1011895/java8u131_java.security.txt)

$ /opt/puppetlabs/puppet/bin/augtool -At "Properties.lns incl /home/jim/Downloads/java8u131_java.security"
augtool> print /files/home/jim/Downloads/java8u131_java.security
augtool> errors
Error in /home/jim/Downloads/java8u131_java.security:1.1 (parse_failed)
  Iterated lens matched less than it should
  Lens: /opt/puppetlabs/puppet/share/augeas/lenses/dist/properties.aug:50.25-.100:
    Last matched: /opt/puppetlabs/puppet/share/augeas/lenses/dist/util.aug:134.6-.14:
    Next (no match): /opt/puppetlabs/puppet/share/augeas/lenses/dist/util.aug:22.27-.34:
augtool> quit
jim@xx:~/my/dev/pup/wtfo
$ /opt/puppetlabs/puppet/bin/augtool --version
augtool 1.4.0 <http://augeas.net/>
Copyright (C) 2007-2011 David Lutterkort
License LGPLv2+: GNU LGPL version 2.1 or later
                 <http://www.gnu.org/licenses/lgpl-2.1.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David Lutterkort

**Comment by qs5779** [comment]
I just discovered the file I was provided was a dos crlf style file. I converted it to dos and it parsed fine. I am new to augeas, so if the tool is line ending sensitive. Then please mark this issue, as user error. Thanks.

**Comment by raphink** [comment]
Indeed, the `Properties.lns` lens doesn't support DOS eol at the moment. I would welcome a PR to fix this if you want to get a go at it.
