### ISSUE TITLE
aug_source returns the path to the root node and not the filename

### ISSUE THREAD

**Issue by thedrow** [hercules-team/augeas#473]
The original intent of #384 was to get the filename containing a node. `aug_source()` uses `path_of_tree()` which returns the root node instead.
I'm not sure this is a bug since `aug_source()` seems like a useful utility but is there a way to reliably get the filename containing the node from augeas without span?

**Comment by lutter** [comment]
What `aug_source` returns is `/files/$path` where `path` is the absolute path to the file, relative to the filesystem root that was set when augeas was initialized (can also be found in `/augeas/root`). To get from the output of `aug_source` to the absolute path in the filesystem, remove `/files` from it, and then prepend whatever is in `/augeas/root` (usually, that's just `/`, and you don't need to do anything)

**Comment by thedrow** [comment]
I guess we can do that. The question is, why do we need span information for the exact filename?

**Comment by lutter** [comment]
The reason that filename is tied to span is that it's usually not needed, and maintaining it requires additional allocations, and is therefore part of the struct that gets only allocated for each tree node when span information is turned on.

**Comment by thedrow** [comment]
Maybe we should just add another flag for filenames without the span information?

**Comment by lutter** [comment]
That would still require extra allocations; can you explain more what the problem is ? It seems in your OSTree code, you would just need to add a `memmove(filename, filename + strlen("/files"), strlen(filename) - strlen("/files") + 1)` before calling `context.setCache`.

That could of course have gone into the `aug_source` implementation, and changing it now would break the API.

**Comment by thedrow** [comment]
I guess you are right.
