### ISSUE TITLE
sshd lense doesn't seem to handle groups with spaces

### ISSUE THREAD

**Issue by davealden** [hercules-team/augeas#477]
Hi,
  I'm having problems using augeas on my sshd_config which has an AllowGroup with a space:

\# grep AllowGroups /etc/ssh/sshd_config
AllowGroups math-domain-users "access admins"
\# augtool print /files/etc/ssh/sshd_config/AllowGroups
/files/etc/ssh/sshd_config/AllowGroups
/files/etc/ssh/sshd_config/AllowGroups/1 = "math-domain-users"
/files/etc/ssh/sshd_config/AllowGroups/2 = "\"access"
/files/etc/ssh/sshd_config/AllowGroups/3 = "admins\""

Help?

**Comment by davealden** [comment]
Anyone?  :)

**Comment by sluetze** [comment]
Hi,
afaik groups under unix should match the pattern "[_a-z][-0-9_a-z]*\$?" as in libmisc/chkname.c and the lense seems to keep to that concept.

i guess the compliant way to fix it would be to fix the groupname to the matching pattern.

disclaimer: i don't work in this project

rgds
-- sluetze

**Comment by davealden** [comment]
Linux allows groups with spaces - I'm not happy about that, but it is what it is.  :)

Our machines are bound to our Active Directory server and the Windows folks seem to love group names with spaces.  There's no way we are going to get them to do away with them.

**Comment by raphink** [comment]
The current allowed value is `/[^ \t\n]+/` indeed. I'd welcome a PR to fix that.
