### ISSUE TITLE
Augeas leaves temporary files when the destination is not writable

### ISSUE THREAD

**Issue by seanmil** [hercules-team/augeas#479]
When an Augeas save is done and the destination file is not writable, the temporary file that Augeas uses is left behind and not cleaned up.

If run from a regularly executing job it can lead to accumulation of a great many temporary files.

The error returned in Augeas is "rename_augtemp" and I believe that the place to fix it would be in transform.c:clone_file but it isn't quite clear to me what the proper implementation of fix would be.

**Comment by lutter** [comment]
I _think_ the way to fix this would be to call `unlink(augtemp)` in the error handling in `transform_save` on line `transform.c:1265`. `clone_file` makes sure that `from` doesn't exist when it is successful (either through `rename` or explicit `unlink`)

In all other uses of `clone_file`, it seems we would want to leave the `from` file untouched when `clone_file` fails, and only when we fail to clone the temporary file should we also unlink it.

**Comment by lutter** [comment]
@seanmil could you have a look and see if PR #493  fixes the situation that gave you trouble ?
