### ISSUE TITLE
Missing new options for Sudoers.aug

### ISSUE THREAD

**Issue by ljkimmel** [hercules-team/augeas#482]
In RHEL7.4 the latest version of sudo (1.8.1p2-10) contains new option(s) which are not captured in the constructed options list in Sudoers.aug. I'm not sure if there are others but 'match_group_by_gid' is one that causes the default /etc/sudoers file to fail parsing.

**Comment by raphink** [comment]
Ok. Could you provide a pull request for these please?

**Comment by ljkimmel** [comment]
I'll be glad to help however I can. I'm not a developer and not familiar with coordinating development with GIT. I was mainly just trying to let you developers know about an issue that I discovered. I didn't make any changes to the code base.
