### ISSUE TITLE
1.9.0 tarball contains tests/lens-*.sh files

### ISSUE THREAD

**Issue by hillu** [hercules-team/augeas#511]
Hi,

I just tried to build augeas 1.9.0 for Debian/unstable, using the tarball from http://download.augeas.net/.

The build process fails quite early because `ln -s` is used to create `tests/test-*.sh` (`$lens_tests`), but those have been shipped as files in the tarball.

**Comment by lutter** [comment]
Those files have been shipped for a long time (at least since 1.0) I just downloaded the tarball and successfully ran `./configure && make && make check`. How are you building ? What exactly is the error message ?

**Comment by hillu** [comment]
My workaround is removing those files before building.

For the Debian package, it is an autoreconf, followed by a regular `configure && make && make install`. You can see the Debian build log for amd64 at <https://buildd.debian.org/status/fetch.php?pkg=augeas&arch=amd64&ver=1.9.0-1&stamp=1507466158&raw=0> or for all architectures at <https://buildd.debian.org/status/package.php?p=augeas&suite=sid>.

The build failure occurred because the files already existed, but make still wanted to build them, using `ln -s`. I could not reproduce the error in the `configure && make` context, but running `make` after `touch tests/lens-test-1` it reappears:

```
Making all in tests
make[2]: Entering directory '/home/bengen/p/deb/augeas/tests'
ln -s lens-test-1 lens-sudoers.sh
ln: failed to create symbolic link 'lens-sudoers.sh': File exists
Makefile:3950: recipe for target 'lens-sudoers.sh' failed
make[2]: *** [lens-sudoers.sh] Error 1
```

**Comment by lutter** [comment]
The problem is that you are running `autoreconf` - that's a developer tool, not something that should be used with a released tarball, which is self-contained and doesn't require autotools. From a released tarball, you should just build with `configure && make && make install`. Is there a specific reason why you are running `autoreconf` ?

**Comment by hillu** [comment]
no, `autoreconf` is not the problem. The "debhelper" tools run it if not specifically overridden.

One problem is that `ln -s` fails to overwrite exisitng files. I have provided a patch fixing that.

Another issue is that the distributed tarball contains copies of the `lens-test-1` script rather than symlinks. (Those do not need to be distributed at all...)

**Comment by lutter** [comment]
I have no idea what debhelper is doing to trigger regeneration of the `lens-*.sh` files - I just ran `autoreconf` on the released tarball, and it worked fine. But to keep things working smoothly on Debian, I'll merge your patch.

It's important though to make sure that the normal `configure && make && make install` cycle also keeps working - we can't make running `autoreconf` mandatory for releases as that would break builds for other distros.

**Comment by hillu** [comment]
@lutter I agree on both points.:-)

I have no clear clue what exactly went wrong, it must have been something related to timestamps.
