### ISSUE TITLE
augmatch name

### ISSUE THREAD

**Issue by sevendials** [hercules-team/augeas#542]
You might have already considered this but you are missing a golden opportunity to name the new tool: augrep

**Comment by lutter** [comment]
Ha .. I had thought about augrep, and discarded it because I didn't feel it was sufficiently close to grep's functionality. But I had never thought about how golden that would have been. Now that it's in a released version, I feel it's too much hassle to rename it. Good observation though.

**Comment by MatthewHannigan** [comment]
In the future you might like to introduce subcommands to overall command.

So you could have `aug sed`, `aug match`, `aug grep` and so one.

Easy to make aliases then.
