### ISSUE TITLE
Append '\n' to work around lenses broken by files without ending newline?

### ISSUE THREAD

**Issue by ciz** [hercules-team/augeas#547]
Lenses are known to be broken when a file doesn't contain a trailing newline.

A similar issue was already opened: [Issue 312](https://github.com/hercules-team/augeas/issues/312)

[YaST](https://github.com/yast) is using augeas to parse the configuration files.
When a file without a trailing newline is encountered, it results in a failure, such as these [two](https://bugzilla.suse.com/show_bug.cgi?id=1074891) [bugs](https://bugzilla.suse.com/show_bug.cgi?id=1080051)

My question is, how to deal with it?
Should the lenses be fixed to accept such files?
Or should a workaround be implemented in augeas itself?

Issue 312 could easily be fixed by patching xfread_file() to append a newline.
The same hack is already implemented by append_newline() in src/transform.c.

The two openSUSE bugs need a different solution.
YaST uses rubygem [CFA](https://github.com/config-files-api/config_files_api).
It reads the contents of a configuration file to a string and then uses aug_set() and aug_text_store().
So the file isn't read by augeas at all, its content gets passed via aug_set() instead.
I'm not sure how to workaround this in augeas. Appending a newline in aug_set() would break things for sure.
Perhaps CFA should take care of it when [loading the file](https://github.com/config-files-api/config_files_api/blob/master/lib/cfa/base_model.rb#L54).

What would be the proper fix to mitigate this issue?

**Comment by raphink** [comment]
I think the best would be to fix the lenses to accept empty strings.

**Comment by lutter** [comment]
I would hugely prefer if that would be taken care of in CFA rather than in Augeas, simply because changing `aug_text_store` will break that existing API. We could add a new call to the API (say `aug_text_store_nl`), but you'd be stuck with the existing behavior until a new release of Augeas becomes available and you update to that, i.e., you'll likely implement this workaround yourself anyway.

I'd rather not try to fix this in individual lenses.

Would that work for you ?

**Comment by ciz** [comment]
I created the above mentioned pull request for CFA. Let's see.

**Comment by ciz** [comment]
The CFA pull request is about to be accepted.
That solves the problem for me.

As you didn't want any changes in Augeas, I'm cloing the ticket.
