### ISSUE TITLE
php.aug: "set" to uncomment existing directives rather than adding new ones

### ISSUE THREAD

**Issue by drzraf** [hercules-team/augeas#550]
Is it doable with the [ini](https://github.com/hercules-team/augeas/blob/master/lenses/inifile.aug) filter the [php.aug](https://github.com/hercules-team/augeas/blob/master/lenses/php.aug) lens currently inherits from?

**Comment by raphink** [comment]
It is not directly doable with Augeas, as comments are not parsed but simply mapped as `#comment` nodes. For this reason, you'll need to:

* parse comments to find it
* insert the value after or before the comment
* remove the comment
