### ISSUE TITLE
Json.lns how to set a value to true or false

### ISSUE THREAD

**Issue by Salokyn** [hercules-team/augeas#559]
Hi,
I try to set a value to "true" or "false".

In lack of a better idea I used the type "string", but I get the following error :
```
Debug: Augeas[transmission-daemon](provider=augeas): sending command 'set' with params ["/file/etc/transmission-daemon/settings.json/dict/entry[.= \"rpc-whitelist-enabled\"]/string", "true"]
...
Debug: Augeas[transmission-daemon](provider=augeas): /augeas/files/etc/transmission-daemon/settings.json/error/message = Fail
ed to match tree
 
     { "const" = "true" }
     { "string" = "true" }
 
  with pattern
 
(    { }
      | { /#comment/ = /[^\001-\004\t\n\r ][^\001-\004\n]*[^\001-\004\t\n\r ]|[^\001-\004\t\n\r ]/ }
      | { /#mcomment/ })*
```

Is there a bool type or something ?

**Comment by lutter** [comment]
I never noticed, but it's a bit wonky: you need to use `const` (possible values are `true`, `false`, and `null`). The easiest way to find something like that out is to create a file that has the content you want. I created `/tmp/test.json` as 
```json
{
  "val": true
}
```

And then had `augtool` print the tree it got from that:
```
> augtool -A -t 'Json.lns incl /tmp/test.json' print /files/tmp/test.json
/files/tmp/test.json
/files/tmp/test.json/dict
/files/tmp/test.json/dict/entry = "val"
/files/tmp/test.json/dict/entry/const = "true"
```
It looks from the output above that you already had `settings.json/dict/entry[.= \"rpc-whitelist-enabled\"]/const = true` in your tree. When you set `string` there to `true` too, `entry` had two children and that's what Augeas was complaining about: it only wants one child for that `entry`, either `string` or `const`.

If that doesn't solve it, could you please include the file and the puppet resource you are using ? I'd be more than happy to help troubleshoot further.

**Comment by lutter** [comment]
Closing this for now. Feel free to reopen if my comment above doesn't address the issue.
