### ISSUE TITLE
nginx: Support semicolons in values

### ISSUE THREAD

**Issue by rgm3** [hercules-team/augeas#566]
I would like to use augtool to parse an nginx.conf file that contains:

```
add_header X-XSS-Protection "1; mode=block" always;
```

Unfortunately, I have not as yet been able to appropriately modify the nginx.aug lens to redefine the statement terminator as "semicolons at the end of the line that are not within double quotes."

**Comment by lutter** [comment]
Have a look at PR #567 - that should do what you want. Please let me know if that works for you. 

I am not familiar with Nginx syntax - if there are other kinds of directives that need this treatment, please let me know, too.

**Comment by lutter** [comment]
I've changed the PR so that the lens now accepts simple directives like 'internal'; there's no whitelist for such entries though, it'll accept 'joey;' just the same as a directive.
