### ISSUE TITLE
Race in building liblexer_la-lexer.lo and parser.h

### ISSUE THREAD

**Issue by zhurikhin** [hercules-team/augeas#572]
Occasionally augeas fails to be built with the following error:
```
[  436s]   CC       liblexer_la-lexer.lo
[  437s] lexer.l:21:20: fatal error: parser.h: No such file or directory
[  437s]  #include "parser.h"
[  437s]                     ^
[  437s] compilation terminated.
[  437s] Makefile:1504: recipe for target 'liblexer_la-lexer.lo' failed
[  437s] make[3]: *** [liblexer_la-lexer.lo] Error 1
[  437s] make[3]: *** Waiting for unfinished jobs....
[  437s] updating parser.h
[  440s] make[3]: Leaving directory '/home/abuild/rpmbuild/BUILD/augeas-1.9.0/src'
[  440s] Makefile:1301: recipe for target 'all' failed
[  440s] make[2]: *** [all] Error 2
[  440s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/augeas-1.9.0/src'
[  440s] Makefile:1397: recipe for target 'all-recursive' failed
[  440s] make[1]: *** [all-recursive] Error 1
[  440s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/augeas-1.9.0'
[  440s] Makefile:1262: recipe for target 'all' failed
[  440s] make: *** [all] Error 2
```
It looks like there is a missing dependency between generation of 'src/parser.h' from 'src/parser.y' and its usage in 'src/lexer.c' generated from 'src/lexer.l'.  Does it make sense?  If yes, from my limited understanding it might be fixed by adding 'parser.h' to the 'BUILT_SOURCES' variable in 'src/Makefile.am'.

**Comment by lutter** [comment]
I've never encountered this error, so it's hard for me to test the suggested fix. Can you confirm that that does indeed fix the issue for you ? If it does, I am more than happy to make the change.

**Comment by pixelb** [comment]
Hit this on a very parallel build. Adding parser.h to BUILT_SOURCES in src/Makefile.am seems to avoid the issue

**Comment by rwmjones** [comment]
Since the fix is really trivial, can we include it please.

https://github.com/hercules-team/augeas/pull/803/files

**Comment by georgehansper** [comment]
The original pull-request was closed when the repository it came from was deleted.

This commit which includes this change 565fabdc48a5bad37987710d38c3449651f7d3f5 has been added to the master branch

For all intents and puposes, merged
