### ISSUE TITLE
httpd lens Apache parsing error with conditional statements and (empty) comments

### ISSUE THREAD

**Issue by joohoi** [hercules-team/augeas#577]
Hi, one of our users stumbled upon an issue where Augeas would fail to parse their configuration. I was able to narrow the exact issue down to a case that is indeed a bit strange looking.

In short: If there's a empty comment line (a whitespace character required after hash) after an [If statement](https://httpd.apache.org/docs/2.4/mod/core.html#if), Augeas fails to parse the file.

Example snippet (GitHub markdown might remove the whitespace after hash):

```
  <If "%{HTTP_HOST} == 'example.com'">
    # 
    Order Allow,Deny
    allow from All
  </If>
```

**Comment by lutter** [comment]
Thanks for reporting this and whittling it down to something I could easily play with. PR #579 should address this issue.
