### ISSUE TITLE
multipath.aug: quotation marks in key-value parameters

### ISSUE THREAD

**Issue by hujkis** [hercules-team/augeas#583]
multipath lens presumes that values that have key-value format will not contain quotation marks.

Our use case:
we have a multipath.conf generated for each array by Red Hat Multipath Helper Tool - access.redhat.com/labs/multipathhelper . eg:
        device {
                vendor "COMPELNT"
                product "Compellent Vol"
                path_grouping_policy "multibus"
                path_checker "tur"
                features "0"
                hardware_handler "0"
                prio "const"
                failback "immediate"
                rr_weight "uniform"
                no_path_retry "queue"

As you can see, all values are in string quotes. Which is completely fine as confirmed by multipath developer.

Snip from multipath.aug:
  |kv "prio" /const|emc|alua|ontap|rdac|hp_sw|hds|random|weightedpath/
  |qstr "prio_args"
  |kv "failback" (Rx.integer | /immediate|manual|followover/)
  |kv "rr_weight" /priorities|uniform/

If we than try to edit the /etc/multipath.conf file using augeas, it will fail.

**Comment by lutter** [comment]
Hi,

sorry for not replying sooner; would you expect Augeas to strip out the quotes or would it be fine for your use to have `"immediate"` as the value of a tree node ? The former is a bit more involved to do ...

**Comment by lutter** [comment]
Actually, this turned out to be easier than I thought, even with stripping the quotes. Have a look and let me know if that change works for you.
