### ISSUE TITLE
ssh.aug does not parse RekeyLimit .. perhaps others.

### ISSUE THREAD

**Issue by mboldi-uptycs** [hercules-team/augeas#605]
I did not do an exhaustive search of all possible entries ...  BUT !!  I did find RekeyLimit that is the Ubuntu default setup.  It happens to be commented out, but it could be set.
RekeyLimit 1G 1h
I did a patch by adding this line to ssh.aug for my own purposes

let rekeylimit = array_entry /RekeyLimit/i

let special_entry = send_env 
     | proxy_command
    ....
      | rekeylimit

**Comment by raphink** [comment]
Fixed in #607
