### ISSUE TITLE
How to undo aug_set when aug_save fails?

### ISSUE THREAD

**Issue by iamkrish73** [hercules-team/augeas#613]
Hi,

In my system there are around 50+ lenses and related configuration files.  What we do is once load the lens files ( aug_init()) when the system is booting up and use the returned pointer in the aug_get/aug_set calls from various submodules and different locations.

Suppose I am trying to change the value of a leaf node with aug_set which is successful, but when I call aug_save(), it fails.  Let the reason be whatever, my questions is:  how do I reset the value I set in previous step, i.e. aug_set?

aug_load is the only way? if so, looks like it is going take long time because all the 50+ lens have to loaded again.  Is there a better way (easy and quick) to handle this scenario?   I was expecting an api something like aug_reset().

Thanks,
Krish

**Comment by raphink** [comment]
To my knowledge, `aug_load` is currently the only option. That said, you can make it faster by only loading the files you want to parse instead of all known files. You can use `aug_transform` or `aug_load_file` (slightly slower, but easier) for this.

**Comment by lutter** [comment]
Yes, `aug_load` is the only way to reset the tree. But it's not as bad performance wise as you think: when you run `aug_load` augeas checks for each file whether any changes have been made to the corresponding subtree or the underlying file, and if not, it does not reprocess the file.

**Comment by lutter** [comment]
I am going to close this because I believe we answered the question. If there is any followup, feel free to reopen.
