### ISSUE TITLE
Postfix master: cannot parse unix-dgram values

### ISSUE THREAD

**Issue by bk2204** [hercules-team/augeas#635]
Using the Debian postfix 3.4.5-1 package in buster, `/etc/postfix/master.cf` contains the following line:

```
postlog   unix-dgram n  -       n       -       1       postlogd
```

This line is rejected because the lens doesn't understand the `unix-dgram` entry, and consequently Augeas can't modify the file since it can't parse it.

**Comment by raphink** [comment]
Fixed in 1e219dbdb9145a5b81c993f691ec2be75099d0bf
