### ISSUE TITLE
Parsing /etc/profile with shellvars.aug

### ISSUE THREAD

**Issue by mboldi-uptycs** [hercules-team/augeas#641]
I use augeas from osquery and ( as you know ) if parsing fails, no rows are returned from the query like "select * from augeas where path = '/etc/profile' "
when profile has a line wiyth && in it ..
like the default ubuntu file has ... && (line2) .. if you take this out, it parses fine ..

```bash
if [ "$PS1" ]; then
  if [ "$BASH" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      source /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi
```

**Comment by mboldi-uptycs** [comment]
Oh, and /etc/bashrc should also be included !!

**Comment by raphink** [comment]
The syntax to parse your `/etc/profile` was added in #582 and released in version 1.12.0.

**Comment by raphink** [comment]
As for `/etc/bashrc`, mine is at `/etc/bash.bashrc` and does not parse with the lens because it's really much more than a configuration file.

**Comment by raphink** [comment]
In particular, the lens doesn't yet support 

```bash
case " $(groups) " in *\ admin\ *|*\ sudo\ *)
```
