### ISSUE TITLE
Is it possible to import back in augeas, the output of a dump-xml command?

### ISSUE THREAD

**Issue by ncarrier** [hercules-team/augeas#656]
Hello,
If it's not possible, is there a way, through augeas, to backup the whole configuration of a linux box and to reapply it at a later stage?

**Comment by raphink** [comment]
I had started implementing this years ago, but it was never finished because merge policies were quite complex.

**Comment by raphink** [comment]
You can see the mentions of this idea in https://www.redhat.com/archives/augeas-devel/2012-April/msg00014.html

**Comment by ncarrier** [comment]
Thank you very much for your feedback, I'm taking a look a the ML thread ATM.

I have an embedded product (**OC**, an option card) plugged in another embedded product (let's call it **HOST**).
I'd like to have the ability to backup the whole configuration of **OC**'s system, and store it on **HOST** so that it can be reapplied as is at a later stage.
So the situation is quite simple, as I want to restore _all_ and I can have the guarantee that the software on **OC** has the exact same version when the backup and the restoration are done.

So if it's not possible to reapply an XML dump, I was planning to (more or less ^^) use the output of the `print` command, iterate over its lines and do the corresponding `set` commands.
Do you think that such an approach could have chances to work? Which hurdles should I be expecting, in you opinion?

**Comment by raphink** [comment]
Augeas won't give you a guarantee of backing up all the conffiles, only the ones it knows about. Even then, re-applying the XML (if it were possible at the moment) would result in losing all specific syntax (indentation, newlines, etc.), as well as file rights (owner/group/mode).

For your need, I'd go with something along the lines of [etckeeper](https://etckeeper.branchable.com/) instead. It allows to version every file in `/etc` and push it to a remote to be restored at a later time.

**Comment by ncarrier** [comment]
Hum, ok, I see that augeas will not be as perfect as I originally though for config backup / restoration.
Because we're already using it for other purpose, I was hoping that it was a good fit for that too.

The etckeeper solution you proposed seems really interesting, thank you.
