### ISSUE TITLE
augtool can not parse systemd unit file with "ConditionPathExists" clause

### ISSUE THREAD

**Issue by anisinha-ntnx** [hercules-team/augeas#665]
```
# ./augtool print /lib/systemd/system/mcelog.service 
[root@demo01-2 bin]# ./augtool --version
augtool 1.12.0 <http://augeas.net/>
Copyright (C) 2007-2016 David Lutterkort
License LGPLv2+: GNU LGPL version 2.1 or later
                 <http://www.gnu.org/licenses/lgpl-2.1.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David Lutterkort
# cat /lib/systemd/system/mcelog.service 
[Unit]
Description=Machine Check Exception Logging Daemon
After=syslog.target

# FIXME - due to upstream kernel bug always start the mcelog process
# twice using the following ExecStartPre hack. This needs fixing.
# There is a bug filed against systemd for the ExecStartPre bit
# since it is not possible to specify that the ExecStarPre bit
# is allowed and expected to fail without aborting the daemon.
ConditionPathExists="!/sys/module/edac_mce_amd/initstate"

[Service]
Type=forking
ExecStartPre=/etc/mcelog/mcelog.setup
ExecStart=/usr/sbin/mcelog --ignorenodev --daemon --syslog
SuccessExitStatus=0 15
StandardOutput=syslog

[Install]
WantedBy=multi-user.target
```

**Comment by raphink** [comment]
This file works for me. Could you please send the output of the following command:

```
$ augtool -At "Systemd.lns incl /lib/systemd/system/mcelog.service" errors
```

**Comment by raphink** [comment]
Ah no, nevermind, you're just not using the right path. The path you want to use in Augeas is `/files/lib/systemd/system/mcelog.service`, not `/lib/systemd/system/mcelog.service`.

**Comment by anisinha-ntnx** [comment]
> Ah no, nevermind, you're just not using the right path. The path you want to use in Augeas is /files/lib/systemd/system/mcelog.service, not /lib/systemd/system/mcelog.service.

# augtool -At "Systemd.lns incl /files/lib/systemd/system/mcelog.service" errors
Error in Systemd (Can not find lens Systemd.lns)
[root@demo01-2 bin]# ./augtool --version
augtool 1.12.0 <http://augeas.net/>
Copyright (C) 2007-2016 David Lutterkort
License LGPLv2+: GNU LGPL version 2.1 or later
                 <http://www.gnu.org/licenses/lgpl-2.1.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David Lutterkort
[root@demo01-2 bin]# ./augtool print /files/lib/systemd/system/mcelog.service 
[root@demo01-2 bin]#

**Comment by anisinha-ntnx** [comment]
So it is not able to find Systemd.lns lens.

**Comment by raphink** [comment]
What OS are you on, and how is Augeas installed (through Puppet, with OS packages, other install option)?

**Comment by anisinha-ntnx** [comment]
OK never mind. My /lib64/libaugeus.so.0 was screwed up. But now when I try to insert "ConditionPathExists" line in mcelog.service, I get:

augtool> set /files/lib/systemd/system/mcelog.service/Unit/ConditionPathExists "!/sys/module/edac_mce_amd/initstate"
augtool> save
augtool> save
error: Failed to execute command
saving failed (run 'errors' for details)
augtool> errors
...
Error in /lib/systemd/system/mcelog.service (put_failed)
  Failed to match 
    
(    { /Description/ }
      | { /Descriptio((n[.0-9A-Z_a-z-]|[.0-9A-Z_a-mo-z-])[.0-9A-Z_a-z-]*|)|Descripti([.0-9A-Z_a-np-z-][.0-9A-Z_a-z-]*|)|Descript([.0-9A-Z_a-hj-z-][.0-9A-Z_a-z-]*|)|Descrip([.0-9A-Z_a-su-z-][.0-9A-Z_a-z-]*|)|Descri([.0-9A-Z_a-oq-z-][.0-9A-Z_a-z-]*|)|Descr([.0-9A-Z_a-hj-z-][.0-9A-Z_a-z-]*|)|Desc([.0-9A-Z_a-qs-z-][.0-9A-Z_a-z-]*|)|Des([.0-9A-Z_abd-z-][.0-9A-Z_a-z-]*|)|De([.0-9A-Z_a-rt-z-][.0-9A-Z_a-z-]*|)|Environmen((t[.0-9A-Z_a-z-]|[.0-9A-Z_a-su-z-])[.0-9A-Z_a-z-]*|)|Environme([.0-9A-Z_a-mo-z-][.0-9A-Z_a-z-]*|)|Environm([.0-9A-Z_a-df-z-][.0-9A-Z_a-z-]*|)|Environ([.0-9A-Z_a-ln-z-][.0-9A-Z_a-z-]*|)|Enviro([.0-9A-Z_a-mo-z-][.0-9A-Z_a-z-]*|)|Envir([.0-9A-Z_a-np-z-][.0-9A-Z_a-z-]*|)|Envi([.0-9A-Z_a-qs-z-][.0-9A-Z_a-z-]*|)|Env([.0-9A-Z_a-hj-z-][.0-9A-Z_a-z-]*|)|Exec([.0-9_-][.0-9A-Z_a-z-]*|[A-Za-z]|)|Exe([.0-9A-Z_abd-z-][.0-9A-Z_a-z-]*|)|(Ex[.0-9A-Z_a-df-z-]|En[.0-9A-Z_a-uw-z-]|(E[.0-9A-Z_a-mo-wyz-]|D[.0-9A-Z_a-df-z-]|[A-CF-Za-z][.0-9A-Z_a-z-])[.0-9A-Z_a-z-])[.0-9A-Z_a-z-]*|Ex|En|E[.0-9A-Z_a-mo-wyz-]|D[.0-9A-Z_a-df-z-]|[A-CF-Za-z][.0-9A-Z_a-z-]/ }
      | { /Exec[A-Za-z][.0-9A-Z_a-z-]+/ }
      | { /Environment/ }
      | { /#comment/ = /[^\001-\004\t\n\r ][^\001-\004\n]*[^\001-\004\t\n\r ]|[^\001-\004\t\n\r ]/ }
      | { /\\.include/ = /[^\001-\004\t\n #]*[^\001-\004\t\n #\\]/ }
      | { })*
  with tree
    { "Description" } { "After" } { "#comment" = "FIXME - due to upstream kernel bug always start the mcelog process" } { "#comment" = "twice using the following ExecStartPre hack. This needs fixing." } { "#comment" = "There is a bug filed against systemd for the ExecStartPre bit" } { "#comment" = "since it is not possible to specify that the ExecStarPre bit" } { "#comment" = "is allowed and expected to fail without aborting the daemon." } {  } { "ConditionPathExists" = "!/sys/module/edac_mce_amd/initstate" }
  Lens: /usr/share/augeas/lenses/dist/inifile.aug:459.27-460.17:

**Comment by raphink** [comment]
If you do a `print` of the tree, you'll notice that `ConditionPathExists` does not have a direct value. Instead the value uses a sub-node called `value`:

```
/files/tmp/test/Unit/ConditionPathExists
/files/tmp/test/Unit/ConditionPathExists/value = "\"!/sys/module/edac_mce_amd/initstate\""
```

So you need to update that sub-node instead if you want the tree to fit through the lens.

**Comment by anisinha-ntnx** [comment]
Ah cool! I guess my expression did not fit the grammar. Thanks!
