### ISSUE TITLE
Modify systemd network configuration

### ISSUE THREAD

**Issue by chruetli** [hercules-team/augeas#682]
I have to edit my network configuration which is located at `/lib/systemd/network/50-external.network` containing 
```
[Match]
Name=myName

[Network]
Address=192.168.1.1/24
```
Unfortunately augtool seems not to parse the path `/lib/systemd/network` as the corresponiding folder `/files/lib/systemd/network` does not exist in `augtool`. 
What do I have to do to get this file parsed?

**Comment by chruetli** [comment]
My solution is adding the path to the `filter`.

    (* View: filter *)
    let filter = incl "/lib/systemd/system/*"
        . incl "/lib/systemd/system/*/*"
        . incl "/etc/systemd/system/*"
    ...
        .incl "/lib/systemd/network/*"

I think this is not possible at runtime. There should be a `augeas` or `lens` lens to fix the augeas config ;-)
Is there a better way to solve it?

**Comment by psztoch** [comment]
It should be added. It is very simple and very necessary.

Patch for `systemd.aug` should include for `let filter = `:
```
           . incl "/lib/systemd/network/*"
           . incl "/etc/systemd/network/*"
```

The need to add is very great.

**Comment by chruetli** [comment]
Done with https://github.com/hercules-team/augeas/pull/683
