### ISSUE TITLE
New chrony.conf options unsupported by chrony lens (sourcedir, ntsdumpdir)

### ISSUE THREAD

**Issue by flo-renaud** [hercules-team/augeas#697]
With Fedora33, chrony-4.0-0.9.pre4.fc33.x86_64 is shipped and provides new options with default values in /etc/chrony.conf that render the lens unusable.

When the default chrony.conf is installed, it contains
```
sourcedir /run/chrony-dhcp
ntsdumpdir /var/lib/chrony
```
and those 2 options break augeas. In order to reproduce, use the following python script:
```
from augeas import Augeas
import os

aug = Augeas(flags=Augeas.NO_LOAD | Augeas.NO_MODL_AUTOLOAD)
module = "chrony"
chrony_conf = os.path.abspath("/etc/chrony.conf")
aug.transform(module, chrony_conf)  # loads chrony lens file
aug.load()  # loads augeas tree

path = '/files{path}'.format(path=chrony_conf)

# remove possible conflicting configuration of servers
aug.remove('{}/server'.format(path))
aug.remove('{}/pool'.format(path))
aug.remove('{}/peer'.format(path))

aug.set('{}/pool[last()+1]'.format(path), "1.pool.ntp.org")
aug.set('{}/pool[last()]/iburst'.format(path), None)

aug.save()
```

The script fails to save chrony.conf with a new pool:
```
# python3 /tmp/test_augeas.py
Traceback (most recent call last):
  File "/tmp/test_augeas.py", line 20, in <module>
    aug.save()
  File "/usr/lib/python3.9/site-packages/augeas.py", line 488, in save
    raise IOError("Unable to save to file!")
OSError: Unable to save to file!
```

If /etc/chrony.conf is manually edited in order to remove the options `sourcedir` and `ntsdumpdir` prior to using augeas, then the script succeeds.

Reproduced with augeas-libs-1.12.0-4.fc33.x86_64 + python3-augeas-0.5.0-22.fc33.noarch

**Comment by raphink** [comment]
Hello,

These options were added in https://github.com/hercules-team/augeas/pull/698. You can pull the new lens from the master branch for now, until a new version is released.
