### ISSUE TITLE
any plans to ship complete source tarballs?

### ISSUE THREAD

**Issue by hillu** [hercules-team/augeas#741]
http://download.augeas.net/ contains source tarballs of older releases. Since the gnulib bits are missing form the auto-generated source tarball attached to the 1.13.0 Github release, the documented `./configure && make && sudo make install` trifecta no longer works

Are you still planning to provide complete tarballs?

**Comment by etherealist** [comment]
@hillu I built the proper tarballs: https://stuff.1042.ch/Sources/augeas-1.13.0.tar.xz

You can also build it yourself:

```bash
git clone https://github.com/hercules-team/augeas.git
git checkout release-1.13.0
git submodule update --init
./autogen.sh --gnulib-srcdir .gnulib/  # This also calls configure which will fail because it adds --gnu-srcdir, but it will do autoconf properly
rm -r .git* .gnulib
cd ..
mv augeas augeas-1.13.0
tar cf augeas-1.13.0
xz -9 augeas-1.13.0.tar
```

**Comment by hillu** [comment]
Alright, thanks. Those steps could of course be run automatically as part of a Github CI job. Or you may want to update the README file which currently gives misleading instructions.

If the augeas project no longer provides ready-to-use tarballs, perhaps the stale http://download.augeas.net/ site should be removed altogether.

**Comment by georgehansper** [comment]
A working tarball can be generated by running:
```
./autogen.sh
make dist
```

This will create a tarball called `augeas-1.13.0.tar.gz`
This tarball includes the required gnulib files

From there, you can build an rpm using
```
mv augeas-1.13.0.tar.gz ~/rpmbuild/SOURCES/
rpmbuild --nocheck -ba --define 'dist .custom' augeas.spec
```

**Comment by hillu** [comment]
I get it. You don't want to provide tarballs that can be used to build binaries as described in the README:

> See the generic instructions in INSTALL. Generally,
> 
>     ./configure
>     make && make install
> 
> should be all that is needed.

Instead of repeatedly telling me how to build such a tarball myself, you may want to get the documentation fixed and get rid of the obsolete download site.

**Comment by raphink** [comment]
We could attach the tarballs to the GitHub releases. That would be easier to manage than the historical download.augeas.net which is hosted by @lutter

**Comment by wangkerong** [comment]
hi！Can you provide the full augeas-1.13.0.tar.gz?

**Comment by kloczek** [comment]
+1

**Comment by kloczek** [comment]
> A working tarball can be generated by running:
> 
> ```
> ./autogen.sh
> make dist
> ```

Please DO NOT USE "make dist".
Please always use "make distcheck"
`distcheck` it is `dist` + try to use just generated tar ball to build everything.

**Comment by kloczek** [comment]
Gentle ping ..

**Comment by hillu** [comment]
> Gentle ping ..

I'm still here. :-)

**Comment by Stream-Punk** [comment]
Distros won't adopt the new version until there is a tarball that works. Either at the orginial location or the github release page. I am still building my own distro-package.

**Comment by hillu** [comment]
Debian has gotten updated packages after @georgehansper told me how I should build a tarball. The README documentation is still wrong and misleading after 3 months, of course.

PR #744 that may have solved this has been sitting there for more than a month, there haven't been any recent commit – by the looks of it, this project is dead and has been for quite some time.
