### ISSUE TITLE
1.13.0: missing dist tar ball

### ISSUE THREAD

**Issue by kloczek** [hercules-team/augeas#756]
Looks like 1.13.0 dist tar ball has not been uploaded to https://download.augeas.net/

**Comment by kloczek** [comment]
gentle ping 😄

**Comment by VorpalBlade** [comment]
Any updates on this?

**Comment by georgehansper** [comment]
#744 has been merged, which will create tarballs on Github for future releases.
As far as I can tell, there is no https version of the site http://download.augeas.net

Someone else will have to answer as the the possibility of uploading tarballs to http://download.augeas.net

**Comment by kloczek** [comment]
> #744 has been merged, which will create tarballs on Github for future releases.

So what abput uploading dist tar ball for 1.13.0? 🤔

**Comment by georgehansper** [comment]
I've uploaded a tarball augeas-1.13.0.tar.gz to the [1.13..0 release](https://github.com/hercules-team/augeas/releases/tag/release-1.13.0)

This is the same tarball as is generated from `make distcheck` and includes the required gnulib code (ie copied from the git submodule).

This tarball is built using the instructions in the file `INSTALL`, which is different to the process used for building from the git repository.

**Comment by prometheanfire** [comment]
looks like the same happened with 1.14.0

**Comment by georgehansper** [comment]
The github action failed to create the tarball automatically.
I have uploaded the tarball for 1.14.0 to

* https://github.com/hercules-team/augeas/releases/download/release-1.14.0/augeas-1.14.0.tar.gz

**Comment by kloczek** [comment]
OK just tesed that tar ball and al look good.
Thank you 👍
