### ISSUE TITLE
oss-fuzz: timeout

### ISSUE THREAD

**Issue by Alan6233** [hercules-team/augeas#807]
Hi Team,

I get an error in ageaus-1.13.0 when doing oss_fuzz test, the details are as follows:

ALARM: working on the last Unit for 25 seconds
and the timeout value is 25 (use -timeout=N to change)
==7== ERROR: libFuzzer: timeout after 25 seconds
#0 0x526981 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:86:3
#1 0x471968 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
#2 0x457129 in fuzzer::Fuzzer::AlarmCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:300:5
#3 0x7f8f0494738f (/lib/x86_64-linux-gnu/libpthread.so.0+0x1138f)
#4 0x55e53b in state_set_index /src/augeas/src/fa.c:629:9
#5 0x55203c in minimize_hopcroft /src/augeas/src/fa.c:1547:22
#6 0x550abd in fa_minimize /src/augeas/src/fa.c:1782:13
#7 0x5505b2 in LLVMFuzzerTestOneInput /src/augeas/augeas_fa_fuzzer.cc:72:3
#8 0x4586f1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:556:15
#9 0x443a52 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:296:6
#10 0x449ae7 in fuzzer::FuzzerDriver(int*, char***, int ()(unsigned char const, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:776
#11 0x472132 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
#12 0x7f8f03f6a82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
#13 0x41e068 in _start (/out/augeas_fa_fuzzer+0x41e068)

**Comment by igalic** [comment]
this looks like https://github.com/hercules-team/augeas/issues/709  ?

**Comment by Alan6233** [comment]
同#709
